### ISSUE TITLE
JSVM log tests now spit output to terminal

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#1002]
```
$ go test
foo
{"x": "y"}
PASS
ok      github.com/TykTechnologies/tyk  2.136s
```

@buger this is likely your recent `rawlog` fix. I might have time for this today.

**Comment by mvdan** [comment]
I'm a bit confused by this fix. Why is `log.RawFormatter` and `log.GetRaw` necessary?

The reason behind the breakage is this regression:

```diff
-               io.WriteString(j.Log.Out, call.Argument(0).String())
-               j.Log.Out.Write([]byte("\n"))
+               rawLog.Print(call.Argument(0).String() + "\n")
```

You've made the JSVM use a global, but I avoided that on purpose because it was racy. You're just lucky enough that nothing else uses `rawLog` just yet - but once more stuff starts using it, data races will pop up.

And, of course, this bit of code in the test doesn't use `buf` anymore, which means the ouptut goes to the terminal:

```
var buf bytes.Buffer
jsvm := JSVM{}
jsvm.Init()
jsvm.Log = logrus.New()
jsvm.Log.Out = &buf
```

**Comment by buger** [comment]
Logs formatting in `logrus` achieved by `Formatters`, it can be JSON or plain text formatters by default, but can be extended. By default logrus outputs to its `Out`, but if you add hooks, it will output to both `Out` and all of the hooks. I checked logrus API, and can't find a way to iterate through list of Hooks and write to them directly. In addition you can't dynamically change `Formatter` of the logger. 

Based on that, I implemented the second logger, with custom raw formatter, because it is the only way to idiomatically implement needed functionality.

Regarding tests output, I will push a fix which uses local RawLog variable, same as `Log` one, so it will write to the buffer in tests.

**Comment by mvdan** [comment]
> Regarding tests output, I will push a fix which uses local RawLog variable, same as Log one, so it will write to the buffer in tests.

What about the races? As long as this tests modifies the global loggers, it's bound to be racy sooner or later.
