### ISSUE TITLE
CORS headers on a per-key basis

### ISSUE THREAD

**Issue by richard-hulm** [TykTechnologies/tyk#112]
When an API key is created, it would be good to be able to add CORS information, at least domains if not the entire range of CORS options (methods etc).

Currently, it's possible to update the API definition with a big list of all the cors headers required, but this leaves the headers in the definition with nothing directly linking them to the user that requested it.

This would also open each user to only asking for the HTTP methods they were using which could make a slight difference in security?

**Comment by lonelycode** [comment]
Thinking about this, it could be quite tricky, because CORS is handled before key lookups happen, since CORS requests tend to be pre-flight in  browser. So no auth is necessarily sent with the OPTIONS request (the client may have no control over this).

Another option might be this: When a user key is created, store their CORS domain in their metadata set with the key object. Then you can at least link domain ownership to a token (if you are using developers, then you could add it to their custom fields set, as this gets copied into a key metadata set on creation).

Then any CRUD actions on the token can also reference the domain list in the api definition using third-party integrations.

Alternatively, we look at making the CORS domain list external to Tyk so it can be easily managed third-party (e.g. a pluggable backend, like redis, consul or etcd). A bit trickier since cORS is handled by a third-party lib.

Needs some more thought, we could always reverse token lookup an CORS, but again there's no guarantee that the client has control over the pre-flight CORS request in-browser.

**Comment by richard-hulm** [comment]
After discussing this with some of our front end devs, it seems we could send back a wildcard to all pre-flight options requests, and then when the actual request comes in, grab the auth key from there and return only the cors data associated with that key for the actual response. This seemed to work in some inital tests we did

**Comment by richard-hulm** [comment]
Just an update on this - currently we're going to serve a wildcard CORS header on all options requests, then lock subsequent requests down by which API they're part of.

Long-term, it would be nice if subsequent requests could have information that is grabbed on a per-key basis, as the wildcard for OPTIONS requests would allow the pre-flight request through, then the actual request with the KEY could have API-Key-specific headers returned on it

Cheers.

**Comment by manjeshpv** [comment]
In browerser I'm getting a cors issue
![image](https://cloud.githubusercontent.com/assets/1999957/10811776/97cf3258-7e35-11e5-997a-9dce2f7e1643.png)

```
options Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.
```
I tried to add header in tyk -> System Management -> Apis -> Edit -> Advanced Options
![image](https://cloud.githubusercontent.com/assets/1999957/10811740/4a5a2d52-7e35-11e5-99b7-dc67fe01f251.png)

**Comment by lonelycode** [comment]
@manjeshpv Interesting, not sure this is the right place for this question as this ticket is specifically for a new feature.

1. Have you tried it with a wildcard allowed origin (i think the allowed origin should just be http://teambnw.com)?
2. Have you tried using a custom header instead of Authorization?
3. You have OPTIONS pass-through enabled, which means that the OPTIONS request is being handled by the rest of the Tyk middleware and being allowed through to your underlying service, which could be writing new CORS headers to the response which could be causing the conflict

To debug, can you share the actual response headers from both the pre-flight OPTIONS and attempted request?

**Comment by manjeshpv** [comment]
@lonelycode Thank you for response, I tried so much permutation and combination with headers in tyk advanced options and my code. Now everything working fine. 

1. My issues is specifically with `OPTIONS` method. I enabled all required CORS headers in my code(.htaccess and PHP).
2. No issues with header
3. Thanks for explaining what is `options passthrough`.

![image](https://cloud.githubusercontent.com/assets/1999957/10842396/3fca87f0-7f17-11e5-8b63-f9618e0e5797.png)

But if disable passthrough and update 
![image](https://cloud.githubusercontent.com/assets/1999957/10842518/3a538f0a-7f18-11e5-8c4b-330eb3752cd0.png)
Below error will come
![image](https://cloud.githubusercontent.com/assets/1999957/10842507/2429db62-7f18-11e5-9f4c-6559b8056316.png)

I read some articles about preflight requests. But I'm not able to understand what is the `OPTIONS PASSTHROUGH` options. Please give me any link of the documentation. Its not found in https://cloud.tyk.io/docs/api-management/advanced-options/

**Comment by lonelycode** [comment]
@manjeshpv When tyk is managing CORS for you, it will basically handle pre-flight requests (which are OPTIONS requests generated by the client) and respond according to your configuration in the dashboard. Tyk will *not* continue proxying that request to your app, that OPTIONS pre-flight request will terminate with the gateway and never reach your application.

Now if you enable the pass through, Tyk will:

1. Write the required headers to the http response steam (keeping the conneciton open)
2. Send the OPTIONS request ON through the middleware to your upstream application
3. Your app will then process it, and potentially add it's own headers to it's response
4. Tyk will take the repsonse from your app, and copy it's headers, body and other data to it's open response stream.
5. It will then flush the buffer to the client and essentially write the whole proxied response back

So, if you have pass-through enabled, and your ap is configured to handle CORS, it could be duplicating the headers that tyk has already added.

By switching it off, you ensure that this can't happen.

Now I've just tried your app (sorry, I was curious), and I can see that all the requests that are going through Tyk Cloud are responding with the correct headers and responding with 200 OK statuses. So you've either resolved the issue, or you are testing with a different application, in which case, what are you using to run these tests, and are they running from the domain you've specified?

**Comment by manjeshpv** [comment]
@lonelycode : Thank you so much for you interest on my questions, No issues if you open app in teambnw[.dot]com This is demo app or POC for micro services Architecture(Learning). 

Tyk cloud is responding because I enabled passthrough.

As per my code show below. My angularjs client or browser want 
1. `Access-Control-Allow-Headers: Authorization, Content-Type `
`Authorization` for Login Enabled in client
`Content-Type` is for swagger(in developer portal)
2. Same origin

```php
 header('Access-Control-Allow-Headers: Authorization, Content-Type');
if(array_key_exists("HTTP_ORIGIN",$_SERVER)) {
                $ref = $_SERVER["HTTP_ORIGIN"];
                header("Access-Control-Allow-Origin: $ref");
            }
```

Question 1: But I don't know, How to send response headers for OPTIONS request in Advanced Options -> CORS. If possible how to return same origin as per the request(shown in above php code)

Question 2: Please send me any articles about how to setup service discovery with etcd and  load balancer.
```js
{
	"node" : {
		"value" : "http://teambnw.com/beatlebuddyapi"
	},
	"target_list" : ["http://mobile.teambnw.com/beatlebuddyapi", "http://teambnw.com/beatlebuddyapi"]
}
```

![image](https://cloud.githubusercontent.com/assets/1999957/10844734/13f2258c-7f28-11e5-9599-ab986a45d4fe.png)

**Comment by lonelycode** [comment]
@manjeshpv ok this is totally the wrong place for this discussion. Please put any further questions in the mailing list.

1. Our CORS middleware sends all the headers automatically, the easiest thing to do is to set a wildcard allowed host "*", this allows everyone access
2. Don't use service discovery until you've solved the CORS issue... you're conflating two issues, please view the documentation on the site, the change log and the version notes for examples for all of these things in action, there's also extensive examples in the service discovery test suite
3. Do not use pass through, you are now conflating two CORS implementations - your apps and Tyk, pick one. The point of CORS is to protect the JS client, so why would your app, if it is being proxied by Tyk, set CORS headers too? In fact, if your app is handling CORS, then switch it *off* in Tyk, since you've already handled it.
