### ISSUE TITLE
Configurable handling of non-2xx responses from upstream endpoints

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1140]
Feature

**What is the current behavior?**
Gateway transparently proxies error responses from upstream endpoints.

**What is the expected behavior?**
Ability to configure how the gateway handles error codes. For example, if an upstream endpoint returns a non 2xx response code etc., option to temporarily disable the host (service discovery) for a period of time, allow passthrough (current functionality), attempt an alternative LB upstream endpoint.

**Comment by mvdan** [comment]
Note that what hosts are included in the load balancer is only determined by the host checker at the moment. Is that not enough? I worry that we would be overcomplicating something that's fairly simple at the moment. Unless this is a common user request?

Attempting a different upstream seems closer to the current behavior. How would we limit this? We don't want it to try all possible upstreams, as that wouldn't scale at all with the total number of upstreams. Should we limit it to a certain configurable number? What should the default be?

**Comment by buger** [comment]
What you describe here is a bit vague. We do handle upstream errors using different mechanisms. 
First of all, you can specify multiple upstream, and we do the health checks to them from time to time: if the host is down we exclude it from the list unless it healthy. 
![image](https://user-images.githubusercontent.com/14009/30675834-4b4fc918-9e9c-11e7-96e6-16abdd8b5e65.png)


If we talking about service discovery, Tyk should not add own logic here, because health checking is the responsibility of service discovery service. 

Additionally, you can add "Circuit Breaker", to temporary disable certain endpoint (recovery time), if certain number of errors found https://tyk.io/docs/ensure-high-availability/circuit-breakers/

**Comment by MangoMM** [comment]
Possibility that I have mistranslated the customer problem. Customer is currently using cloud solution. And `uptime tests` not available for cloud. 

If one of the LB upstream targets returns for example a 500 or 404 error, instead of returning the error back, customer was looking for the ability to loop over the other upstream endpoints and temporarily take the failing endpoints out of the LB (0% circuit breaker).

**Comment by buger** [comment]
What you described here is exactly what we have for round-robin load balancing, which I mentioned as first thing in my comment. Are you sure this is not available for the cloud users?

Another option for this customer is to use external load balancer like AWS Elb or even nginx, to perform all this logic, and point Tyk to use LB endpoint.

**Comment by lonelycode** [comment]
Uptime tests are not available for cloud users due to data storage constraints.

**Comment by MangoMM** [comment]
There may be scenarios where adding LB outside of Tyk may not be feasible / possible. Further, using LB with health-checks say every 60s, means that there could be a potential 60s period where the service is down, and the LB doesn't yet know about it.

Having option for Tyk to retry another upstream target in the hope of a +ve response 2nd time round could be a nice value-add. Obviously constraints such as number of retries, or response codes received from target to trigger the retry would need further discussion or ability to configure.

If you think is worth exploring, I can add to Trello roadmap.

**Comment by mvdan** [comment]
I think there are two different proposals here - one is trying different upstreams if the selected one is perceived as down, and another is making the load balancer aware of down upstreams by using them instead of (or as well as) using the periodic host checker.

They would both use similar information, but the features and outcomes are different.

I think the first is worth exploring, as it seems generally useful. It seems like the design wouldn't be as simple as it would originally seem, though - we should avoid the shortcut that is buffering all requests all the time.

The second one I would still think not, but given that Cloud doesn't have the host checker, it might be. I'm 50/50 on it. @buger, @lonelycode, thoughts?

**Comment by buger** [comment]
So, we already have LB support with periodic checks.

I assume that @MangoMM means in case of issue retrying without any checks, with the different upstream target, which is next in the list. Right?

**Comment by buger** [comment]
Worth noticing that retrying request is a very tricky since a lot of requests are not safe to retry since they can modify application data, and error not always comes because the host is not available, same with timeouts (sometimes they are kind of ok, just require timeout tuning).  

What can be done, in case of failure we may notify `GlobalHostChecker` about it, so upstream failure will be triggered earlier, but it still requires having Host checker feature (it depends on Redis), and it is not available for the Cloud (but Hybrid is ok).

**Comment by lonelycode** [comment]
> Worth noticing that retrying request is a very tricky since a lot of requests are not safe to retry because they can modify application state, and error not always comes because the host is not available, same with timeouts (sometimes they are kind of ok, just require timeout tuning).
