### ISSUE TITLE
API Groups support

### ISSUE THREAD

**Issue by yoanisgil** [TykTechnologies/tyk#115]
Hi,

I was wondering if you have plans to add support for API groups. As the name explains an API group is a collection of APIs a user can create and consume using a single API Key. This is not an strange concept on an API ecosystem and WSO2 already has a similar concept, though they called applications. I imagine this could be a bit tricky to implement since it impacts every aspect of the life cycle of an API, the dashboard and the portal. So for now I just wanted to know your thoughts on it.

Bests,

Yoanis.

**Comment by lonelycode** [comment]
You can give a token or a policy access to multiple APIs. 
When you create a key take a look at the access rules (same goes for policies) - you can add as many Apis and versions to a key or policy as you like so that you can create a policy that enables access to a group of APIs that you're managing with Tyk:
https://tyk.io/v1.8/quotas-limits-security/limiting-access/

**Comment by yoanisgil** [comment]
Ok. I will take a look but it did not look like there's a UX/UI flow in the portal which lets you do that. Is that correct?

**Comment by lonelycode** [comment]
In the portal, you can publish an API catalogue entry that is tied to a policy, the policy grants access to multiple APIs
That policy is the applied to the token generated for the developer.
Developers can't control anything about their keys except request them and monitor them. It's quite intentionally limited to ensure access control remains with the API owner.
You could publish multiple catalogue entries that give different access rights Via different policies. Then the developer can have multiple keys that represent those groups.

**Comment by yoanisgil** [comment]
@lonelycode that's precisely what I wanted to avoid (i.e a developer having to manage multiple keys that represent different groups). Say I have two API:

- Weather API (which uses a third-party weather API)
- Customer Service API (which is an in-house API)

Wouldn't it be a nice to have if developers could just create an API group or application, say "My Cool Application" and have the APIs described above to be part of such application and consume them using the same API key? I think the users would benefit from a simplified workflow, not to mention that there won't be the need for a human to plumb all the stuff required through the creation of policies, etc (because it would be automated at subscription time).

I think it's an idea worth looking into it since it adds a higher level of abstraction which favours API composition and re-use. If you think it's a good idea I will be more than happy helping to implement this ;)

Bests,

Yoanis.

**Comment by lonelycode** [comment]
@yoanisgil I see what you are getting at and I can see the possibilities.

Tyk definitely supports this kind of work-flow (simply modifying user keys' access permissions, but placing that control user-side instead of owner-side). So writing a portal would be quite simple, you would need to do away with managing anything within Tyk Dashboard though. No change needed on Tyk side

Adding this to the existing portal is a bit tricky, the current flow is very much based on policies and keys being linked with developer accounts, wht you are proposing is a completely different mode of access - i.e. a developer is allowed access to API A, B and C, but has no token, they then generate a token for A+B and another for A+C and maybe one for A+B+C. 

Policies stratify these rules into groups so that many keys can be managed en-masse. The above flow would mean no policies (so no way of ensuring you disable or catch errant tokens), or decoupling access control from policies using another policy (ouch, especially on a per-token basis), or inverting the access control override chain from being "policy overrides key" to being "key overrides policy" (but since keys without access control lists enable global access, this would be a bad thing and is disabled by default as a security measure, integrators can chose to switch this off though).

Policies enable API owners to control hundreds of thousands of keys with a single setting (including their rate limits and quotas), instead of managing those keys independently (remember in many setups keys are hashed, so they are not even visible to the API Owner unless they retained a copy of the raw key), enabling this kind of composition on the portal end breaks all that management of keys en-masse.

While I like the idea of having an API owner expose 10 different APis via the portal and allow devs to compose their own access controls, the argument for complexity vs. payoff just doesn't hold (I save a dev a line in their configuration file for an extra token, while we need to implement a whole new security layer for compositional keys), remember that dev still needs a wrapper or library to access that API, especially if it has more than one resource - so where's the practical benefit?.

Tyk has APIs that handle key access-control composition, both via the Advanced and Gateway API, if an integrator wants a compositional interface, they can quite easily set one up and just bypass the Tyk portal altogether and not use policies (or they could use aspects of it, then modify the keys themselves). The system is very flexible for devs wanting do things their way, so it's not like it's impossible, just the argument for building it into the (non open source) portal isn't strong enough.

Will leave this ticket open, if there's more interest would be happy to come back to it.

**Comment by senj** [comment]
I wonder if a policy can really grant access to and manage multiple APIs.

The dashboard states on key creation: 
``` All keys can be assigned to a policy, a policy determines the rate limits and quota assigned to a key. Policies override manual settings. ```
It's also impossible to create a key without access rights (is there a setting i missed?)
``` Failed to create key, keys must have at least one Access Rights record set. ```

**Comment by lonelycode** [comment]
A policy object is just the same as a key session object, and the Access Rights value in the policy is copied over the key when it comes in:

https://github.com/TykTechnologies/tyk/blob/master/handler_success.go#L82

(If you use the dashboard, you'll see that you can set access rules on policies), you can also add granular rules on a method / path regex basis to create really custom access modes.

> It's also impossible to create a key without access rights (is there a setting i missed?)

Since policies *override* token values, the token needs a base set (in case the policy gets deleted), so you need to give them access to something (or nothing), even with a policy. You can override this in your tyk.conf by [enabling `allow_master_keys`](https://tyk.io/v1.9/configuration/configuration/#allow-master-keys:a66b35d20295cb764719ac8bd35837ec). This will allow access rules to be empty, use with caution. Should be fine on a small install.
