### ISSUE TITLE
Add support for JQ transformations

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1161]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Right now it is quite hard to apply advanced body and header transformations without middleware. It would be nice to have a more flexible way.
**What is the expected behavior?**
JQ is a very popular library for transforming JSON records. In fact, it is not just a library, it is a mini-language. It would be great to include JQ transformations for JSON based request and responses.

**Comment by buger** [comment]
Created for https://github.com/TykTechnologies/tyk/pull/1044

**Comment by nickReyn** [comment]
@buger can we discuss this please, if it has any ux implication?

**Comment by lonelycode** [comment]
I think in order to make it usable we will need some kind of help text.

`jq` is a very powerful JSON transformation CLI tool, and this issue binds the core library of that tool into Tyk and makes the `jq` command pipeline available to the user in the body transform system.

So for example, in the current system, there's a bunch of stuff you can do with Go templates to transform JSON data, but with `jq` you can do specific JSON stuff like search through an array, find specific fields and even subfields and modify those. It's extremely powerful and extrmeely complex.

So from a UX perspective, I think first steps would be to make sure the user knows they can use JQ notation to do stuff, with a bunch of associated examples, and then later, what would be *really* cool, is a syntax checker in the UI that makes sure the commands are sane (take a look at regexr).

**Comment by nickReyn** [comment]
@lonelycode @buger
Ok cool. I'm still a bit in the dark on where the user has the touchpoint here. Is it a backend journey or is there some UI journey in the Dashboard? There is the body transform section in the Endpoint designer, is it that?

> make sure the user knows they can use JQ notation to do stuff

I'm guessing this means in the documentation, if it's a backend only journey? If there is a UI element I guess we can list the languages/syntax that we support above the code editors, like below?

![jq-transform](https://user-images.githubusercontent.com/15945383/33713889-dc0a3fbc-db44-11e7-89b1-88f932e8bf36.png)

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for JQ Transforms](https://trello.com/c/2OthliOF/506-add-support-for-jq-transforms)
