### ISSUE TITLE
Expanding the HMAC implementation

### ISSUE THREAD

**Issue by alexzorin** [TykTechnologies/tyk#118]
Background: We have a lot of ad-hoc APIs and I am thinking (doing an exploratory integration) about putting them behind a standard gateway such as tyk, if only for AAA benefits. 

So, my interpretation of the docs (https://tyk.io/v1.1/access-control/hmac/) is that the implementation of request signing only signs the `Date` HTTP header. 

Is this a matter of not enough resources to implement the referenced spec fully? The implementation is currently very weak as-is, all it does is prevent replay attacks after a `+- clockSkew` window.

Incomplete list of things it does not protect against:
* Manipulation of POSTed request data (because request body is not signed, but apparently possible via `Digest` header))
* Manipulation of other headers (because you only sign `Date` header)
* Manipulation of request verb and URL (doable via `request-line`, called `request-target` in latest draft spec)
* Replay within `+- clockSkew` (because there is no nonce, and spec does not provide concrete advice here)

So, is this being worked on? Will you accept contributions to expand the implementation in these respects (headers, request line, request body and nonce), any qualifications?

There is also a much newer version of the draft that has some improvements, worth reviewing.

**Comment by lonelycode** [comment]
We've not extended this feature yet because nobody has asked :-) (and yes, resources are thin).
I'd be delighted to accept contributions towards making the HMAC middleware more compliant, so if you fancy taking it on, would be more than happy to help out.
Like with anything, if demand for this feature grows we'll put more work into it to make it better. So far HMAC demand has been pretty low (and usually when someone does want it, it's a very specific implementation they want)
Personally I'd love to get this implementation fully spec compliant, so would be keen to see it get done. If there's time/space at the end of this dev cycle I might take a look at it.
If you want to contribute (that would be great) - please work against the develop branch, not master.
What do you think?

**Comment by alexzorin** [comment]
Sounds good, I hope to get a bit better acquainted with Tyk in a couple of weeks and to take a crack at it.

**Comment by lonelycode** [comment]
Fixed in develop:

- `request-target` now supported
- `headers` signature field is now supported (this means `Digest` can be included)
- Clock skew has always been configurable on a per-API basis
