### ISSUE TITLE
Add a new column "Alias" to view keys in dashboard

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk#1285]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When you configure the Dashboard and Gateway with hash_keys=false, it is possible to view the list of keys in backend. But there is only one column with the hash of each key.

**What is the expected behavior?**
It would be more friendly 
to have another column with the alias of each key to find easily a key from it alias.

![capture du 2017-11-13 16-55-48](https://user-images.githubusercontent.com/1773969/32735159-524fb382-c894-11e7-93ce-4eb89bf9e02d.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
dashboard 2.3.9

**Comment by buger** [comment]
Doing this will probably require making the query for each key, to get its details, but I assume doing this only for the current page with pagination should work, since amount of queries will be not THAT big, like 20-30 keys per page. It probably makes sense add a new endpoint to GW too, to fetch multiple keys at once. We need to think how to make it work from a performance point of view.
