### ISSUE TITLE
Tags in key removed after using

### ISSUE THREAD

**Issue by jesucarr** [TykTechnologies/tyk#131]
These are the steps to reproduce:
- Create a key (for example from Keys > Add Key) and copy it.
- Go to Keys and Look Up the key. The tag is correctly listed.
- Make a request using the key in the authorization header.
- Go to Keys and Look Up the key. The tag is not there any more.

Is this a bug?

**Comment by lonelycode** [comment]
Are you using a policy? A policy will overwrite a keys tags

**Comment by jesucarr** [comment]
Yes I'm using a policy. But in the dashboard it says that "Tags can also be applied at a key level". So I would expect that if I add tags to the key, the policy would respect that key, and add the new keys from the policy. Is there any reason not to behave like this?

**Comment by lonelycode** [comment]
Yes we'd like it to do that too, the reason it doesn't do it is more to limit GC and CPU cycles, extending an array is expensive, overwriting a pointer is cheap. So policies overwrite instead of merge. Since policies are applied in real-time, we try to make that really lightweight.

Maybe we should modify it so that policies don't overwrite tags, but instead are referenced again at the analytics writing level and do the merge there (it's not happening during request throughput, but in a goroutine so it might be ok there). 

If you have middleware that is reliant on tags (e.g. header or body transforms that reference session data or dynamic middleware) then it will only have access to key-level data, which isn;t ideal... 

An alternative might be to have a secondary field in a key we can add to.

Leave this ticket open, we'll consider it as a feature request.

**Comment by jesucarr** [comment]
I understand you don't want to extend the array in real time, and I agree. 

I think the idea of a secondary field is good. Maybe you can have keyTags, and policyTags. This way analytics/middleware can use both or just one of them as needed.

**Comment by lonelycode** [comment]
:+1:
