### ISSUE TITLE
End point Url Analytics at key level

### ISSUE THREAD

**Issue by tandonraghav** [TykTechnologies/tyk#135]
Hello,
I want to see the analytics per key level which mean that what Urls are hit per key level and it will be good if we have method(GET/PUT..) level filters as well.
I see the information is being recorder in mongo DB but not seen in Dashboard.
This will be a generic requirement as people may want to see the Endpoint popularity per key level.

**Comment by lonelycode** [comment]
Yup, think it's definitely something that can be done for the dashboard - the data is mostly there, just need to understand what the filters would be and how they would be used and graphed.

It's too late for the next version, but can go in the roadmap - it would help to have a better idea of exactly how this would break down, I can't visualise the UX / screens / graphs right now - but it might be just because it's late :-)

**Comment by tandonraghav** [comment]
1. Analytics based on per key usage (Endpoint usage/key)
2. Having method level filters.
that's ok...please try to consider this in your path.. :)

**Comment by lonelycode** [comment]
Don't close it dude! ;-) will keep open for further discussion...
