### ISSUE TITLE
Way to specify TLS Ciphers

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1372]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Right now only default set of ciphers is supported
**What is the expected behavior?**
Security standards vary across companies, and there should be a way to whitelist allowed ciphers
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.4, master

**Comment by buger** [comment]
Should be straightforward to implement.
Ciphers specified via `TLSConfig#CipherSuites` array.

List of available constants defined here https://golang.org/pkg/crypto/tls/#pkg-constants

It would be a good idea if instead of using uint8 type in the config, we will create string mapping for this constant with friendly names, so it will look like:

```
"http_server_options": {
...
"ciphers": ["RSA_WITH_RC4_128_SHA", "RSA_WITH_3DES_EDE_CBC_SHA", ...],
...
}
```

**Comment by buger** [comment]
@joshblakeley would you like take care of it?

**Comment by joshblakeley** [comment]
SGTM

**Comment by asoorm** [comment]
@buger @joshblakeley - I think this is great idea. but I think it's worth doing some planning before we go ahead implementing array of ciphers.

OpenSSL has standard way of listing ciphers. e.g. `:` separated list with optional `+`, `-` and `!` modifiers. They also have aliases.

https://www.openssl.org/docs/man1.0.2/apps/ciphers.html

We could build PoC in-line with standard way of doing things (e.g. whitelist in the openssl standard form), then add functionality further down the line if required?

Some more resources for review.

https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslciphersuite
http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ciphers
https://wiki.mozilla.org/Security/Server_Side_TLS

I can just imagine the next requirement/feature request would be to use Strong Diffie-Hellman Group & perfect forward secrecy via ECDHE instead of RSA key exchange.

**Comment by lonelycode** [comment]
I would suggest starting simple and just using a list. Feels like pre-optimising for a non-problem using the OpenSSL format. 

We would basically be implementing a list as a string with directives, which then needs to be parsed and interpreted correctly.

If we ever get someone saying “but why can’t I just cut and paste my ssl directive from my nginx config” then we can look at adding another way of setting these rules, but it just seems overly complicated to me when a list would be just fine? Or am I missing something here?

**Comment by asoorm** [comment]
If we have a list e.g. a whitelist of acceptable ciphers. Then a new cipher is used. Wouldn't this mean that it wouldn't be accepted? Doesn't that mean that the api owner will need to constantly keep on-top of the cipher suite?

**Comment by buger** [comment]
Agree. Looking at AWS implementation it is just an array (on UI it is bunch of checkboxes).

**Comment by buger** [comment]
If new chipher is added it should not be accepted by default. If company have own security policy on chipher, they should manually update list all the time they want to add or remove new one.

**Comment by asoorm** [comment]
Ok, cool - just wanted to check. But I think as part of this feature - we need to document supported ciphers.
