### ISSUE TITLE
Multi-Factor Authentication (MFA)

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1423]
This is a public epic to plan out **Multi-factor auth (MFA) on the Dashboard and Portal.**

As an added layer of security we should add MFA to our Dashboard and Portal.

As of release v0.3 of TIB users can configure TIB with IDP providers that support OpenID. Some of these IDPs provide MFA capability, which means currently you could achieve MFA with Tyk using that method. 

However, does this meet the requirements of our users?

### Community input
We need input from the community to determine the requirements for MFA. Please comment below with anything you can add to this.

**Comment by mikarintala** [comment]
Hi!
Our organization is primarily interested in TYK Hybrid and MFA is pretty much a must for us.

**Comment by letzya** [comment]
Hi @mikarintala
Unfortunatly it's not possible for the time being.
If you check the code of TIB which is open source, you'll see that it makes use of Dashboard Admin API calls (secret is in the tib.conf), and since you can't had admin access to the dashboard on the cloud (which is managed by us) you won't be able to achieve that at the moment.

**Comment by letzya** [comment]
If you have an on-prem we have a step-by-step guide (soon to be a blog post as well) to [implement that](https://tyk.io/docs/integrate/sso/dashboard-login-okta-tib/) with Okta as an Idp

**Comment by letzya** [comment]
@mikarintala ,
I have checked and although this isn’t a standard Tyk cloud service, it might be possible to create a custom package for you. Please can you send your contact details to info@tyk.io to discuss?
