### ISSUE TITLE
Advanced URL rewriter should support negative logic

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1446]
**Do you want to request a *feature* or report a *bug*?**
feature

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Right now I can define only what should match. Introducing negative logic can simplify boolean logic a lot. I would suggest adding "not_match_rx" field.

**Comment by LuanvP** [comment]
This is mainly finished on this branch: https://github.com/TykTechnologies/tyk/pull/1601

I've updated StringRegexMap to include both a MatchPattern and a NotMatchPattern. The Check method takes both of these into account.

I've added tests to cover negative and mixed-logic cases, there is one test commented out which was behaving strangely and it seemed to be due to some caching behaviour in the way the tests were run (?)

**Comment by buger** [comment]
Closed in favor of https://github.com/TykTechnologies/tyk/pull/2096

**Comment by ilijabojanovic** [comment]
Released in 2.9 release
