### ISSUE TITLE
Tyk Dashboard to run inside Apache Server not on 3000 port

### ISSUE THREAD

**Issue by tandonraghav** [TykTechnologies/tyk#145]
Hey,

Just want a quick thought on this. I want tyk-dashboard to run inside a Apache Web Server as I cannot open a 3000 or other ports. 
mod_proxy is also not working as your page might load other Urls as well. 
Can you tell me how can i put Dashboard under Apache web server and get access to dashboard.

**Comment by lonelycode** [comment]
There's a better way to do this, you can proxy the dashboard using Tyk itself :-)

Basically - since Tyk Gateway can handle domain management, you can set up Tyk to proxy the HTTP requests just like NginX or Apache does, we've made it bootstrappable with an API call, to set up the proxy configurations, simply run:

`curl -d "domain="{PORTAL-DOMAIN}"" -H "admin-auth:{ADVANCED-ADMIN-API-SECRET}" http://YOUR-DASHBOARD-INSTANCE:3000/admin/organisations/{YOUR-ORG-ID}/generate-portals`

In a terminal

Here:

- `PORTAL-DOMAIN` must be a standard domain form, no protocol or slashes, so e.g. `www.my-portal.com`.
- `ADVANCED-ADMIN-API-SECRET` Must be the `admin_secret` value of your `tyk_analytics.conf` file
- `YOUR-DASHBOARD-INSTANCE` probably `localhost`, given you can't access from outside. If you've set a dashboard domain in the tyk_analytics.conf file, then you'll need to disable tyk Dashboard host management as you'll be using Tyk Gateway as domain manager
- `YOUR-ORG-ID` is the value under "System Management" -> "Users" -> Your user -> "RPC Credentials, basically the organisation ID for all of your APIs and the portal you are building

This command will create three APIs in your dashboard, they will reverse proxy from Tyk Gateway (which I assume you have running on port 80) to your dashboard and assets for you, binding to your preferred domain name, however this command assumes that the Tyk Dashboard instance is on localhost.

These APIs have some special properties - they have a `do_not_track` setting so they don't mess with your analytics, and they also are marked as a "site" so they appear greyed out (they are still editable though).

This is what we do in the docker instance where everything is on the same host and want it all to work over port 80.

Alternatively, if you must use apache, you will need to proxy/rewrite:

- `/api/` to `http://localhost:3000/`
- `/portal-assets/` to `http://localhost:3000/`
- `/` to `http://localhost:3000/{YOUR-ORG-ID}/portal/`

This will proxy the *ROOT* of the domain that apache is managing to be the portal, if you want it elsewhere, change the last proxy rewrite to something else

**Comment by tandonraghav** [comment]
Alternatively, if you must use apache, you will need to proxy/rewrite:

   - /api/ to http://localhost:3000/
   - /portal-assets/ to http://localhost:3000/
   - / to http://localhost:3000/{YOUR-ORG-ID}/portal/

The problem is if i do */ to http://localhost:3000 <http://localhost:3000>*
then only it works as apache is not aware of /login and other stuff.
So, is there a prefix which you use so that all the urls are routed to
localhost:3000 without using the Root?

**Comment by lonelycode** [comment]
Ah I see. You still want the dashboard to work on port 80 too. My suggestion would be to have the dashboard work on a different hostname then, so you set up Apache to proxy everything to hostname A to the dashboard, and hostname B to the portal using the above rewrites.

You need to split it out somehow, you can't have the portal on the same hostname as the dashboard. In our docker config we bind the dashboard to tyk_dashboard.tyk_dashboard.local and the dashboard to a separate host name.

**Comment by tandonraghav** [comment]
I have proxy in apache as /dashboard http://localhost:3000/

then do I need to change in tyk_analytics.conf
"host_config" : {
        "override_hostname": "localhost",
        "disable_org_slug_prefix": true,
        "enable_host_names": true,
        "hostname": "dashboard",
        "portal_domains": {},
        "portal_root_path": "/portal"
    },

I am sure i am missing something here, but not able to make it work.
My requirement is when I hit http://localhost/dashboard it should go to Tyk
dashboard.

**Comment by tandonraghav** [comment]
Ok.. I got it, Virtual hosts are working using Apache...Thanks for your
reply. If you can just clear the doubt of Role of override_hostname and
hostname that would be great.

"host_config" : {
        "override_hostname": "localhost",
        "disable_org_slug_prefix": true,
        "enable_host_names": true,
        "hostname": "dashboard",
        "portal_domains": {},
        "portal_root_path": "/portal"
    },

**Comment by lonelycode** [comment]
Override_hostname will basically just force Tyk Dashboard to assume what the Tyk Gateway hostname is when it uses it in the GUI (it's purely aesthetic)

Hostname is the hostname the the dashboard binds to, it's extremely strict.

**Comment by tandonraghav** [comment]
Got it..Thanks for your help. Your responsiveness is commendable.

**Comment by tandonraghav** [comment]
Hey, Just wanted to check, do you have any security settings to block or revoke user access when the password is entered wrong multiple times in tyk-dashboard?

**Comment by lonelycode** [comment]
No, not yet. but good idea.

Want to open a feature request?

**Comment by tandonraghav** [comment]
Actually that would be good.

**Comment by tandonraghav** [comment]
Hey,
I was able to do path based routing in previous version after creating two apis with urls as:-
Listen Path /test/v1 - Authorized (key)
Listen Path /test/v1/notify - Open Keyless

But now in v1.9 I am not able to do that it keeps on expecting 'Authorization field missing'
Do you have any parameter to enable that??

**Comment by tandonraghav** [comment]
Hey Martin,

Can you please let me know whats the issue. As I tested on earlier release and it was working but suddenly in new release its not working?

**Comment by lonelycode** [comment]
V1.9 handles domains internally, and when it attaches listen paths, it doesn't put them in length order, so the router may be matching your closed API instead of he Open one.
You can address this by either:
- re adding them in a different order, longest path first (we need to address this anyway)- setting a fixed hostname on one API and not the other, they will then be matched differently

**Comment by tandonraghav** [comment]
Oh no but this will cause a problem as all the keys are attached to particular API ID , deleting and adding again the API in different order will make those keys non working. 
But this was working in previous release, so I assume this is changed in 1.9. 
What do you mean by fixed hostname on one? is this an alternate?

**Comment by tandonraghav** [comment]
So, what do you this is good, should i put all the endpoints as APIs? As this will give me more control over authorization. As of now I have only the base url as API.

**Comment by lonelycode** [comment]
If you've set up Tyk 1.9 you can add a custom hostname to an API, so you could just bind the longer listen path to a domain. See here enable_custom_domains here:

https://tyk.io/v1.9/configuration/configuration/

You should be able to add the custom domain using the new version of the dashboard.

To be honest I'm surprised it worked in previous versions as that logic hasn't changed much.

There's another hack you can use and that is the sort_by parameter in the Tyk API definition, it's used by the system to sort API's by force (not documented).

You will need to add a sort_by field to the root of the API definition in Mongo for each API with different integer values and they will sort accordingly. You may need to experiment.

**Comment by tandonraghav** [comment]
I tried adding custom domain as 'localhost' as i dont have any other domain name.
I am not getting this second solution of adding sort_by, is it a mongo level config or tyk level?

**Comment by tandonraghav** [comment]
Do you mean adding entry in /etc/hosts and then configuring that in custom domain. I cannot do that in production.
Please give me the second approach sort_by.. And yes it is working smoothly in previous release and now i am stuck.

**Comment by lonelycode** [comment]
Ok, I think `sort_by` is the solution you need here.

You will need the **latest** version of dashboard for it to work, as yes, otherwise the values will be overwritten as older versions do not support this new API Definition schema.

To enable the `sort_by` field, you need to edit the API manually in MongoDB OR use the Advanced API to update Dashboard.

Here's an abriged DB entry for an API definition with sort_by set:

```
{
  _id: ObjectId("5654565430c55e3904000002"),
  name: "Closed",
  ...
  domain: "",
  do_not_track: false,
  tags: [],
  hook_references: [],
  is_site: false,
  sort_by: 100
}
```
Setting this value in the DB, then hot-reloading the gateway will load up the correct API.

### The other option

How do you target your API? via http://localhost/api/v1/notify?

If so, add "localhost" to domain for one of your APIs and make sure custom domains are enabled (all this is documented in the site).

This creates two route entries, one for the root domain of the gateway, and one for the other API. This is more of a hack, Id suggest the sort_by method, we use this to make sure that that domain listings are in the right order for portal proxying.

**Question**: Why is ` /test/v1/notify` a separate API, why not just have it as a reserved ignored path in the API designer of the first API, if you set this to be ignored, it will bypass the auth altogether and have the same effect?

**Comment by tandonraghav** [comment]
I am using the latest version of dashboard, and by overridden ````sort_by```` means the dashboard is overwriting the value to 0 again, 
<b>Question</b> How to set this value from ````Advanced options````, not able to see that , is it hook??

Using endpoint designer i was able to ````ignore```` the Endpoint but I wanted to have it whitelisted also, which mean only specific IP's hitting that url, but as I make it ````whitelist```` the other paths stop working giving 403 error.

My config:-
Listen Path /test/v1 - Authorized (key)  - target http://localhost:3625/test/v1 - ````No domain````
Listen Path /test/v1/notify - Open Keyless - - target http://localhost:3625/test/v1/notify - <b>localhost (custom domain)</b>

on hitting http://localhost:<tykPort>/test/v1/notifications - still giving authorization field missing.

<b>Answer</b> I am creating a seperate API as i want the analytics and whitelisting for that.

**Comment by lonelycode** [comment]
Q: I am using the latest version of dashboard, and by overridden sort_by means the dashboard is overwriting the value to 0 again, 
A: Are you sure you are not overwriting the data by saving the dashboard entry over the DB one (you need to refresh the API in the designer to load the new data) - this is quite easy to do by accident :-)

 Question How to set this value from Advanced options, not able to see that , is it hook??

A: sort_by is an internal value, it's not exposed to the dashboard yet except to respect it when saving. We use it in the docker setup and in that setup we ask users to change the config in the dashboard, and sort by remains in place, so we know for a fact that it is not overwritten by the dashboard.   

Q: Using endpoint designer i was able to ignore the Endpoint but I wanted to have it whitelisted also, which mean only specific IP's hitting that url, but as I make it whitelist the other paths stop working giving 403 error.

A: You need to whitelist all paths, a whitelist is not an IP block, it stops other endpoints except those specifically listed from working.

**Comment by JosephEarl** [comment]
I'm running Tyk through Docker (v1.9) and I'd also like to be able to expose login to the dashboard on port 80, e.g. portal.domain.com for the portal and dashboard.domain.com for the dashboard both on port 80.

**Comment by lonelycode** [comment]
That's easy, just change the port configuration in Tyk_analytics.conf and use the domain feature to expose the domains.

Then run the gateway on a separate instance so that there is no port conflict.

**Comment by JosephEarl** [comment]
Yes I thought I could do it pretty easily if the dashboard was running on a separate instance - I may do that, but would be nice to have it all running on one small instance if possible.

**Comment by lonelycode** [comment]
Then you will need to proxy the dashboard and portal via the gateway, exactly how we describe it in our documentation for running Tyk in docker:

https://tyk.io/v1.9/setup/docker/

**Comment by JosephEarl** [comment]
I have followed that and setup 2 CNAMES from dashboard.domain.com and portal.domain.com to the instance DNS. However dashboard.domain.com resolves the same content as portal.domain.com, but using port 3000 on either domain works to access the dashboard.

**Comment by lonelycode** [comment]
Did you set the domain name for the portal in the site entries in the dashboard APIs view?

https://tyk.io/v1.9/setup/docker/#one-last-thing-for-your-portal:69e60651f42783a7df723575c4088b5b

**Comment by JosephEarl** [comment]
Yes for each 3 entries I've changed the custom domain to use portal.domain.com and the target URL to use ambassador_1:

* Portal: portal.domain.com, listen path: /, target URL: http://ambassador_1:3000/56a917b7b477e60001000001/portal/
* Portal API: portal.domain.com, listen path: /api/, target URL: http://ambassador_1:3000/
* Portal Assets: portal.domain.com, listen path: /portal-assets/, target URL: http://ambassador_1:3000/

I don't see anywhere in there about setting a host name for the admin dashboard to be dashboard.domain.com though, unless that's what I should be putting there?

NB: I did not edit the hosts file on the instance itself to point 127.0.0.1 at dashboard.domain.com like I did when testing locally since that was taken care of with DNS.

**Comment by lonelycode** [comment]
It might be the fact you are using a CNAME, the host header might not be making it through the proxy properly, have you tried an A record to point at the IP?

**Comment by JosephEarl** [comment]
I've tried the v1.9 setup instructions again locally - and although it says it everything is available on port 80 the setup script tells me to login at port 3000 not 80; I do have 2 entries in my hosts

```
<docker-machine ip default> www.tyk-portal-test.com
<docker-machine ip default> default.docker
```

but am unable to login to the dashboard anywhere but port 3000

**Comment by lonelycode** [comment]
Ah, wait, yes - sorry, there I was thinking you were trying to access the portal, but you want dashboard on 80 too. That's super tricky, as you would need to expose the entire dashboard / dashbaord API through the gateway - you could try to add an APi entry similar to the portal one, bind it to your dashboard domain and proxy it internally to 3000.

No guarantee that will work though, it's just not designed to have the portal, dashboard and APIs all listening on 80 without outside help.

You could use our host manager and NGinX, but that's a pretty major change that doesn't fit here.

**Comment by JosephEarl** [comment]
Thanks will give that a try out, but maybe I'll have to be happy with port 3000 - this is mainly for dev/test environments so that's OK. 

For production I'll look at running the dashboard on a separate instance.

**Comment by JosephEarl** [comment]
PS -- I tried creating a new API named "Dashboard" with the custom domain "dashboard.domain.com" and listen path "/" -- but had no luck. Will try splitting the dashboard and gateway across separate instances.

**Comment by lonelycode** [comment]
It's not something we've tried to set up, though it should be possible to just proxy it through with a domain name. Needs investigation...  I'm pretty sure it should work with Tyk doing the proxying.

**Comment by JosephEarl** [comment]
I tried A records, that didn't seem to help. Also tried doing it locally with the Tyk quick start and adding 2 hosts entries for www.tyk-portal-test.com and www.tyk-dashboard-test.com, setting the built-in 3 APIs to the first and adding a new dashboard API for the second.

**Comment by lonelycode** [comment]
Right, so I got this to work:


1. Kill all your containers, including Mongo, we need a fresh start here
- Edit the `tyk.conf` to add `"enable_custom_domains": true` to the end of the object (make sure it validates as JSON).
- Edit the `tyk_analytics.conf` and set `"portal_root_path": "/"` (it defaults to `/portal`)
- Start the containers with compose
- Run the setup script
- Now edit the APIs for the portal replacing `localhost` with `ambassador_1`
- Now edit the `Portal` API and change the listen_path to `/` (it might already be this)
- Add a new API and call it `dashboard`:
    -  Custom domain:   `www.my-dashboard.com`
    - Listen path: `/`
    - Target: `http://ambassador_1:3000`
    - Auth: Open
- Save it and wait for the Tyk Gateway to reload

Since the quickstart is just that, a way to get started with the portal, the APIs and the dashboard, we don't do strict domain matching (otherwise generic domains wouldn't work properly and other weirdness).

If you enable custom domain on the gateway, then it will enforce listen paths on a domain level instead of root, but adds the requirement of a strict domain path to all APIs - if you look at your logs for the gateway, you'll see your dashboard API is probably being skipped because of a dupe listen path.

So, now you have a portal (on root, at `www.tyk-portal-test.com`), and a dashboard (on root, at `www.my-dashboard.com`)

I would suggest to add another hosts entry:

    192.168.99.100    apis.my-dashboard.com

And then when you create your APIs, bind them to this domain.

All possible, just not with the cookie-cutter quickstart config, it needs tweaking :-)

**Comment by JosephEarl** [comment]
@lonelycode Thanks for all of your help, great support. If you have a repo for docs happy to contribute - I think having info on how to run the compose script on a remote Docker machine would be great (I had to make some modifications for this - mainly including the config files in the gateway/dashboard image rather than mounting them).

**Comment by lonelycode** [comment]
Thx :-)

All the content is here:

https://github.com/lonelycode/tyk-io-site-content

Looking forward to contributions!

**Comment by JosephEarl** [comment]
I noticed one issue with my setup - when I go to my portal and go to view the interactive docs for my catalogue it tries to send me to http://portal.domain.com/apis/apis/56aa28998b529b000100000d/documentation/ which gives a 404.

It looks like the correct URL is (without the double /apis/apis) http://portal.domain.com/apis/56aa28998b529b000100000d/documentation/ which works fine. 

Do you know how I can fix the link displayed in the portal? 
Or should I add another API with the listen path /apis/?

**Comment by lonelycode** [comment]
You can edit all the templates in the portal, so you can just remove that from the template, because of the super odd configuration, Tyk is trying to be clever to guess the right doc location.
