### ISSUE TITLE
Dashboard won't let me edit multiple catalogue entries.

### ISSUE THREAD

**Issue by johnjelinek** [TykTechnologies/tyk#146]
I can only edit the first catalogue entry via the dashboard.

![portalcatalogue](https://cloud.githubusercontent.com/assets/873610/11698512/928f4f8e-9e84-11e5-8c56-ff5bef0c04b5.gif)

**Comment by lonelycode** [comment]
Are they both linked to the same policy?

**Comment by lonelycode** [comment]
Note to self: add validation.

**Comment by johnjelinek** [comment]
I believe they are linked to the same policy.

**Comment by lonelycode** [comment]
That'll be it - generate a new policy and link it to the first API Catalogue entry, save it, and editing will work again.

Will leave this open as we should handle this gracefully :-)

Why is the same policy set up for the two different API entries?

**Comment by johnjelinek** [comment]
I dunno, I thought it would work.

**Comment by johnjelinek** [comment]
There another challenge. If I have only 2 policies and 2 APIs, I have to create a 3rd policy in order to switch them because of the change selection. I can't select none and if I select the same as the other API then the problem persists where only 1 catalogue loads.



—

**Comment by lonelycode** [comment]
Ah, yeah that should be fine, you can totally duplicate policies - it's just catalogue entries that are coupled to policy uniqueness, not policies to API's... They are meant to be varied (e.g trial policy for API 1, pro policy for API 1, enterprise policy for API 1 etc).

**Comment by Klaboe** [comment]
@lonelycode : Two things: 

Is there a reason why one should not be able to have the same policy on two different API-entries in the Catalogue? I mean it is plausible to have multiple APIs that will have the same access rights and rate-limits... But have different documentations? 

Also: If i have two API-entries in my Catalogue that share the same policy; trying to edit the second one will put me in editing mode for the first one....

This seems like bug in the dashboard?

**Comment by lonelycode** [comment]
@Klaboe 
 
>Is there a reason why one should not be able to have the same policy on two different API-entries in the Catalogue?

It's an abstraction we didn't deem necessary -policies are cheap, so you can always have more than one - it offers more control and more traceability than just blanketing a single policy across multiple catalogue entries.

> I mean it is plausible to have multiple APIs that will have the same access rights and rate-limits... But have different documentations?

It is possible, but then it's also incredibly easy to just set up a second policy for that documentation set. 

The catalog is mainly meant for generating a public facade to a group of internal microservices, so you might actually have 100 services you bundle into a single public-facing API, now you use a policy to grant access to a subset (as a trial) and full (as Pro) and it's all transparent to the end-user because APIs are organised on a slug basis, so it all seems like one API even when it is being used.  At least that's a preferred use case.

> Also: If i have two API-entries in my Catalogue that share the same policy; trying to edit the second one will put me in editing mode for the first one....
> This seems like bug in the dashboard?

Yes it is a bug, the workaround is to not have the same policy for two catalogue entries.

**Comment by Klaboe** [comment]
I see, but i still think it would be nice to have the option to have the same one over multiple APIs :)

A "workaround" (which in this case is "dont screw up") is all good, but is it going to be fixed? I mean, it was reported a year++ ago.

**Comment by lonelycode** [comment]
It's not going to be changed, but we'll be putting a check in place to prevent users from doing it.
