### ISSUE TITLE
Endpoints not declared in api designer should send back a 404

### ISSUE THREAD

**Issue by adrien-candiotti** [TykTechnologies/tyk#152]
When you specify endpoints with the api designer and you try to reach a route that is not specified you get an {"error": "Requested endpoint is forbidden"}.

This is not correct and can be misleading to an API user : if he mistypes the route he will not understand what's is going on even if his credentials are working.

Do you think a 404 with the appropriate message could be send back?

**Comment by mvdan** [comment]
My assumption is that if we used 404s, anyone could "discover" the endpoints without having access to them.

A lot of websites that require login do this - if you try to access a resource, it will 401/403 instead of doing a 404.

I'm not sure if this was by design of if it's a bug, though.

/cc @lonelycode @buger

**Comment by lonelycode** [comment]
By default Tyk will 404 even if yu have items in the endpoint designer. 

However is you white list those endpoints thenyou get the error you describe.

This is by design, since white lists enforce access rules.

**Comment by gwshaw** [comment]
We did this in our current gateway and found a lot of user confusion. We decided that if they have a valid api key then we distinguish between 404 (a route that does not exist) and 403 (you don't have permission for that route). That deal with the "discover" issue and aids the user. For our case, we want to make it easy for people to use the APIs and are not trying to hide anything, only monitor access and usage by the key.

**Comment by lonelycode** [comment]
As suggested earlier, disable the white list. This will stop the 403s on non-listed paths. Swap them tonne tracked instead.

If you do not have each endpoint in a white list then it will 404 - swagger imports create white lists by default (which I assume is what happened here), you actually don't need to register anything in the endpoint designer unless you are doing something to the path or want to track it.

In other words: remove all the endpoints in the designer and you will get 404s for bad paths and 403s for bad keys.

The change we may want to introduce is that for swagger imports we generate a tracked list instead of a white list. 

White lists purposefully obfuscate the facade of an api, even for users with valid keys (considering they may have escalating roles - brute forcing discovery of the non-accessible endpoints could be achieved by testing response codes)
