### ISSUE TITLE
[Dashboard] Pagination could use some improvement.

### ISSUE THREAD

**Issue by polds** [TykTechnologies/tyk#154]
First off, I know this repo is for the Gateway, is there any better place to note Dashboard bugs?

The pagination in some of the analytics pages could use some addressing. Looking at the "Endpoint Popularity" page we see something like this:

![screen shot 2015-12-14 at 9 21 08 am](https://cloud.githubusercontent.com/assets/2372558/11786502/35c08e08-a244-11e5-8210-c00ef95002b4.png)

.. and it's still growing. 

This is largely impart because many of our APIs are parameterized, shopping cart ids, user ids, process ids, etc. So the analytics see's that as a separate endpoint each time.

**Comment by lonelycode** [comment]
Snap :-/

This is the right place for this kind of thing. We'll look at making this a bit better.

You can increase the page size in the tyk_analytics.conf to bring it in a bit.

**Comment by polds** [comment]
Just a thought:
A pipe dream of mine would be to logically group parameterized APIs together, so we could see if something like a "profile" endpoint is being called more than anything else. But because every endpoint has a user id in it it's hard to gather that info. 

I'll look at the page size in the conf file. Thanks.

**Comment by lonelycode** [comment]
That could be done, if we modify the white-list, then you define the patterns for the list and add an option "Group by List Entry" or something like that, then we tag the analytics entries by their matching whitelist pattern instead of their actual values.

We would need to copy the masked values to a real field so that we don't lose the data.

I like the idea :-)
