### ISSUE TITLE
Authorization field missing

### ISSUE THREAD

**Issue by lexkong** [TykTechnologies/tyk#1541]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
1. I create a new api use the following json:
{
      "name": "cbmi",
      "slug": "cbmi",
      "api_id": "61",
      "org_id": "1",
      "definition": {
          "location": "header",
          "key": "x-api-version"
      },
      "version_data": {
          "not_versioned": true,
          "versions": {
              "Default": {
                  "name": "Default",
                  "use_extended_paths": true
              }
          }
      },
      "proxy": {
          "listen_path": "/calculator/bmi",
          "target_url": "http://xxxxxx:8889/calculator/bmi",
          "strip_listen_path": true
      },
      "active": true
  }

2. try to access the api:
curl -H "Content-Type: application/json"  -H "x-tyk-authorization: 352d20ee67be67f6340b4c0605b044b7"  http://xxxxxxx:8080/calculator/bmi-5
{
    "error": "Authorization field missing"
}

3. try to add Authorization key:
curl -H "Content-Type: application/json"  -H "x-tyk-authorization: 352d20ee67be67f6340b4c605b044b7"  -H "Authorization: 1" http://xxxxxx:8080/calculator/bmi-5
{
    "error": "Authorization field missing"
}

**What is the expected behavior?**
can access the api

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

**Comment by asoorm** [comment]
If you need to supply an auth header, then in your API Definition, you need to specify the Auth Header Name.

```
    "auth": {
        "auth_header_name": "authorization"
    },
```

As an aside, `x-tyk-authorization` is a header reserved for controlling Tyk, rather than to use as auth header for your own APIs. with the above snippet, you should be able to send an API request as follows:

```
curl -H "Content-Type: application/json" -H "Authorization: 1" http://xxxxxx:8080/calculator/bmi-5
```

**Comment by lexkong** [comment]
I try this way but still got Authorization field missing

#curl -H "Content-Type: application/json" -H "Authorization: 1" http://localhost:8080/calclator/bmi-5
{
    "error": "Authorization field missing"
}

**Comment by asoorm** [comment]
Did you fix the API definition and reload / hot-reload the gateway?

**Comment by lexkong** [comment]
thanks for your answer, I just create the api, found tyk return : 
{
	"key": "62",
	"status": "ok",
	"action": "added"
}

and do nothing.

also why i need to reload or hot-reload the tyk?

thanks!

**Comment by asoorm** [comment]
The response: `{"key": "62","status": "ok","action": "added"}` indicates that you have created a key, or are using the keys endpoint rather than creating an API.

Check this video tutorial on the basics of getting up and running with Tyk Gateway: https://www.youtube.com/watch?v=YFU2HLeT0HY&t

If you don't want to hot reload, you could just store your API definition in the apps directory, and gateway will load it when you start.

**Comment by lexkong** [comment]
thanks very much, i will learn the video and try again

**Comment by buger** [comment]
Will close for now

**Comment by laxmikantm** [comment]
Hi,
How to handle this in postman, while you're sending test request & need to send JWT token as part of Authorization?
Thanks
