### ISSUE TITLE
profile performance of BenchmarkRewriter

### ISSUE THREAD

**Issue by dencoded** [TykTechnologies/tyk#1662]
Let’s focus on significant performance improvements, the ones with less than 1%-5% difference can be just statistical noise (consider to increase bench time with flag `-benchtime=…` in case of low throughput).

Need to do profiling of all types (cpu, memory, block and mutex). Provide `benchcmp` results for benchmark output - before and after improvement (or prove that this piece of code cannot be improved in any ways).

**Comment by matiasinsaurralde** [comment]
I've found a related issue here, at some point we refactored the API definition code in order to avoid pointers when loading `URLSpec` data structures, see [here](https://github.com/TykTechnologies/tyk/commit/c2f80ff6bac2f2c7c92c559be3ae02a452a5c882#diff-e174c6f6100dfee8c74de8323d464e36). This assumed all `URLSpec` access was read only, which isn't the case for the optimization that's described here:
While trying to optimize the URL rewriter middleware I noticed it wasn't possible to pre-compile the regular expression and store it as part of `URLRewriteMeta`, in [`mw_url_rewriter.go`](https://github.com/TykTechnologies/tyk/blob/master/mw_url_rewrite.go) we use the following condition:
```go
	if meta.MatchRegexp == nil {
		var err error
		meta.MatchRegexp, err = regexp.Compile(meta.MatchPattern)
		if err != nil {
			return path, fmt.Errorf("URLRewrite regexp error %s", meta.MatchPattern)
		}
	}
```
This is called every single time and the compiled regular expression isn't persisted (as we expect). To fix this it would make sense to use `[]*URLSpec` again and refactor the functions that use it, mainly `APISpec.Version`, `CheckSpecMatchesStatus`, `MakeSpec`. I've did this and the code seems to work as expected, looking for suggestions anyway.
