### ISSUE TITLE
Failed to call purge: Access Denied

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1669]
**Do you want to request a *feature* or report a *bug*?**

unsure

**What is the current behavior?**

Gateway 2.5.2 (hybrid)
Randomly seeing this in the logs occasionally `Failed to call purge: Access Denied`

**Comment by bitsofinfo** [comment]
Any thoughts on what this would be?

**Comment by buger** [comment]
Hello! Apologies for the delay.

First of all, nothing to worry about, it automatically self-heal. 

The message itself means that MDCB asked Gateway to provide login details (your API key and Org ID). This can happen when our MDCB server gets restarted due to update or auto-scaling event. Such situations are automatically handled by Gateway, and in this particular case, we need to better handle such error in this purge function and do not show such error.
