### ISSUE TITLE
Tyk Gateways Allows Invalid 3 Character Authorization Tokens

### ISSUE THREAD

**Issue by mreines** [TykTechnologies/tyk#1681]
**Do you want to request a *feature* or report a *bug*?**
This is a bug
**What is the current behavior?**
Any API using Authorization header with Tyk AuthToken (key) that has an access list (not using Profile) lets all requests through that have 3 charactors or less in the Authorization header

**What is the expected behavior?**
Obviously these are not valid keys and should be blocked.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create an API, Create a Key for the API, make a request to the API with any 3 character combination. Now try a 4 charactor combination

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
We saw this in Gateway version 2.3.5 through 2.6.1
![api 3 chars](https://user-images.githubusercontent.com/1219269/39766921-5715f54e-529a-11e8-9106-24ed714d8b84.png)
![auth 4 chars](https://user-images.githubusercontent.com/1219269/39766923-573becfe-529a-11e8-97b6-8a7d300f6cf1.png)

**Comment by lonelycode** [comment]
*NOTE: We have not managed to replicate this in our cloud environment*

Agreed that this is a serious issue, however to scope it -  I believe this is because this is in a sparse keyspace environment (there are few tokens issued and few APIs on the system).

The simplest way to mitigate it at the moment is to disable key hashing in the tyk.conf, this should completely resolve the problem (the underlying cause is in our hashing lib).

We are actively working to resolve this issue.

**Comment by buger** [comment]
We can't replicate issue yet. @mreines any chance you can send us your tyk.conf and api definition to support@tyk.io?

We added some protection here https://github.com/TykTechnologies/tyk/pull/1692, and it will be included in 2.6.2, which planned in less than 2 weeks, but we really need a way of replicating it.

Thank you!

**Comment by ilijabojanovic** [comment]
Verified
