### ISSUE TITLE
Separate target URLs for Versioning

### ISSUE THREAD

**Issue by iwat** [TykTechnologies/tyk#169]
Hi there,

Is there any existing way to configure separate target URLs for versioning?
For example:
/api1/v1 -> http://old_server/v1
/api1/v2 -> http://new_server/v2

So that developer can leave old server as is and focus development on the new server without interrupting existing users.

If none is available, do you have any suggestion how to patch this?

**Comment by lonelycode** [comment]
It's been requested before. The simplest thing would be to add an override target field to the version definition object, then have the proxy use that instead.

The problem here is that the proxy object is created during the bootstrap load of the API definition, so it's set in stone. That would need to be changed, which could be quite difficult.

That, and that there are many manipulation a to the target, can cause compounding issues with other features.

So it can be done, but we were waiting for a major version change to introduce it as it's pretty severe.

**Comment by iwat** [comment]
Seems like I have to wait for the next major version while applying a workaround by separating API definition for each version.

**Comment by lonelycode** [comment]
Afraid so, there's something to be said about dynamically creating the proxy at runtime instead of at init, but I worry about performance impact and the side-effects with all the other path-manipulation and target-manipulation features (e.g. service discovery, load balancing - how would that work on a versioned basis?)

**Comment by lonelycode** [comment]
So I had a bit of an experiment here and have a working version in the [`experiment/multi-target`](https://github.com/TykTechnologies/tyk/tree/experiment/multi-target) branch.

You will need to pull tykcommon again as I had to update the `APIDefintion` object.

If you set an `override_target` on the version definition, then it will override the base target, if this value is empty, it will use the base target.

Obviously, clever things like service discovery and round robin aren't supported. But for this use case, it should work.

There's potential to move the various options for the proxy into the version definition, but there's a lot of scope for side-effects, so will need to investigate. For a simple target override though, it shouldn't be a problem.

Take a look and tell me what you think :-)

**Comment by yoanisgil** [comment]
@lonelycode is this available for Docker? I kinda need a similar feature, not urgent though, and I could give it a try.

**Comment by lonelycode** [comment]
Not yet, you'd need to compile it yourself and then insert it into the container manually.
