### ISSUE TITLE
In-memory and distributed quota proposal

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1761]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Requests with quotas hit redis on each request to incremeent their respective quotas, this is wasteful.

**What is the expected behavior?**
We should reduce the number of round-trips to redis

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

## Proposal:

As proposed by @dencoded, to reduce the number of calls to redis, we could make the calls periodic and change how we store quotas. 

I was thinking we could use a redis hash which we update with a redis transaction (multipls `HINCR` calls wrapped in a transaction or a pipeline - there are issues here with Cluster).

To make the updates work across a gateway cluster, we increment a server-based `total` with a gateway based `local` count, and then after that transaction we pull the new totals back into our local quota map and base quota violations on the `total+local` count, resetting the local count to 0 as the total count should be the "integrated" value from the entire cluster.

I've created an [in-memory chnnel-based quota counter](https://github.com/TykTechnologies/inmem-quota) (that should be thread-save), that can also handle snapshots and merges.

The approach leaves a  margin for error as the counts are integrated at a periodic interval, but that *should* be ok so long as they are small. 

With this approach:

- There are no writes to redis per requst, so redis traffic is no longer a function of actual traffic, redis writes will be at specific intervals (e.g. every 5s)
- Quotas are calculated and enforced in-memory per-gateway and are updated with channels so should add minimal latency
- This mechanism can be extended to MDCB, and  allow for quotas to be merged across clusters, solving the global quota problem.

The quota lib also has a Clean() method, that will purge keys over a certain "last-update age" from the list, that could be used to clean the master server list too (or in the case of MDCB it could run the Clean function on behalf of the clients)

Opinions please...

**Comment by dencoded** [comment]
I've been looking into this problem as well and come up with some thoughts, mostly matching what was mentioned by @lonelycode. However, I thought there should be simpler solution, probably I am missing something while saying that solution is simpler.

Some summary about things we have at the moment.

We are limiting number of requests on two levels:
1. Organization session quota
2. API key (aka key session) quota

Both levels use the same implementation from `SessionLimiter` method `RedisQuotaExceeded`

We use Redis as a centralized storage for all quota-counters so in case of several gateways serving traffic quota will be counted correctly (unless Redis is available).

Problem.

`RedisQuotaExceeded` implementation calls `store.IncrememntWithExpire` (we have typo in that method btw) which leads to hit storage with `INCR` and if it was the first request for current quota renewal interval - it also calls `EXPIRE` providing quota renewal as expiration interval.

As to key format in Redis - it uses QuotaKeyPrefix + keySession.KeyHash() so it tracks quotas per keys (API key sessions or org sessions) just fine.

All this makes sense and works fine but has performance problems:

a) it hits Redis to increment counter for every single request with API key containing quota
b) if organization limiter is enabled and has quota - it hits Redis to increment counter for every request no matter which key used in that request (quota limiting for organizations has been added recently)
c) in case of RPC setup - it does RPC call for every request to increment session quota counters - for both cases a) or b)

a) or b) itself produce storm of calls to Redis and introduce lots of network traffic, basically Tyk gateway gets bounded by performance of Redis and network capacity. Also, I think it degrades Redis connections pool in case of high throughput to API with key containing quota.

c) makes Tyk gateway to be network bounded and also can lead to degradation of RPC backend because of storm of calls.

Solution.

We give users a choice (via config values):

- Use current implementation as a fine grained control over quotas and declaring that for high throughput it won’t scale well. However, in case of RPC setup and leaving current implementation as is - performance still needs to be addressed.

Or

- Use new implementation which doesn't hit Redis per request (more scalable) but has less precision in quota limiting, i.e. if key has quota 1000 requests you might get passed through 1005 requests in the given renewal interval before gateway starts responding with 429.

I think that choice can be a compromise between control and performance - users will decide depending on their use cases.

As to new implementation - I'd suggest that flow:

1. Leave logic in `RedisQuotaExceeded` as is with exception to part where we update counter in Redis (call to `store.IncrememntWithExpire`).

2. If config is set to use current implementation then just use current implementation as a short path in logic. 

3. If config set to use new implementation we will have new logic in play.

For new logic I suggest:

- In storage implement new method `IncrementByWithExpire(key string, incBy int64, expire int64) int64` which does inside `INCRBY` Redis-operation for the given key incrementing by `incBy`, if returned result is equal to `incBy` that means new renewal interval started so in that case we also set expiration with command `EXPIRE` 

- Implement the same method `IncrementByWithExpire(key string, incBy int64, expire int64)` in `RPCStorageHandler` with call to RPC server and implement `IncrementByWithExpire` on RPC server side as well.

Do some kind of cycle as new requests arrive to MW:

- if aggregation period is done - do `current_total = IncrementByWithExpire(key, local_counter, renewal)` to overwrite `current_total` from central storage. Reset `local_counter` to 0 and start new aggregation period.

- if `current_total` >= key quota then start responding with 429 and keep `local_counter` as 0 (don't increment)

- if `current_total` < key quota then increment `current_total` by 1 and increment `local_counter` by 1,  respond with 200

That approach probably sounds confusing so I've got a branch to illustrate idea: https://github.com/TykTechnologies/tyk/commit/a4dabee64596bbdc31cdc65737a2427bc6a21ec6

Downsides of this approach:
- if aggregation period ends by the time when new renewal period started (key in redis expired or re-added by other gateway) - we will increment current renewal period with number from previous renewal period
- gateway is living in ideal world during the aggregation period thinking that quota is not exceeded, however key quota can be already exceeded for the key by other gateways by the end of aggregation period of this gateway - as a solution, any gateways should issue special notification when some key's quota is exceeded, so all others will stop counting and start replying with 429 with no increment by end of aggregation period
- in case of RPC we will have some unpredicted network latency which can be a problem. say we have key with quota 100 and renewal rate 1 second, we set config to have aggregation period to be 100ms so key quota counters will call RPC to send local increments and update total from central Redis every 100ms synchronously, what if RPC latency takes 150ms?

**Comment by lonelycode** [comment]
I only just got round to reading this today, this seems pretty reasonable, we don’t really do quotas at a rate of 1s, so I wouldn’t be too worried about latency vs. Timeout in the RPC quota scenario. 

Sounds sensible to me, we basically aggregate locally, then merge and flush to server periodically.

An enhancement I can think of is that the solution here is basically a poor-mans CRDT, but I feel that having a single central counter might be prone to race conditions, we might actually be able to simplify this by actually using a regular CRDT structure:

- Each gateway has a unique ID
- For each token, we create a redis Hash, with a field for the gateway ID, e.g. with 3 gateways and one token with quota we have a redis key that has three fields
- As each gateway receives traffic, it increments an in-memory counter
- After the aggregation period, it increments the redis key.gatewayID hash field by its in-mem total
- The gateway then uses HGETALL to fetch the whole hashed set for the key
- If there is a “blockUntil” field in the set, stop and block the request
- if there’s no block sentinel, the gateway adds all the field totals together (the merged CRDT value for the cluster)
- If the total is larger than the quota, add a “blockUntil” field to the quota key that has a value of seconds to when the quota renews (it should then update the EXPIRE)

Then when the key expires, a new CRDT gets built by the cluster.

(As a sideline benefit, this will also improve the moving quota window issue as the EXPIRE can be set exactly to a calendar date).

As for implementation I don’t think it’s much different to what Den has suggested above, just making the structure cleaner (as the CRDT can scale with a gateway cluster and will retain information even if a gateway shuts down after the scaling event).

For RPC scenarios we may need a secondary  merge that gets the CRDT values from MDCB and merges it with what’s local, or just pass it through - it depends on how often the gateway flushed and the load it puts on RPC (you need to merge for each token, might want that call to MDCB to be a batches operation)

**Comment by lonelycode** [comment]
Im not sure I fully understand this bit :

> if current_total < key quota then increment current_total by 1 and increment local_counter by 1, respond with 200

Why would we increment current_total?

**Comment by lonelycode** [comment]
Just looking at the chunked limiter PR, this is a different approach to the one set out above, or am I misunderstanding?

**Comment by dencoded** [comment]
@lonelycode you are right, this conversation relates to other approach - I needed to update here to clarify that we are exploring new approach

**Comment by dencoded** [comment]
I have implemented a very simple prototype with "chunked quota" - where all slaves are requesting chunk of quota from master-DC and then use it.

There is scenario when some slave have traffic but central DC doesn't have any chunks left for the current quota-period, then the less loaded slave in the same group will "re-fund" some part of its current chunk back to master DC (there are some complications with this scenario described on PR and possible solutions).

There is also a potential performance improvement for non-DC as GW doesn't hit redis within every request processing.

tyk PR: https://github.com/TykTechnologies/tyk/pull/1916 (recently rebased on master)
tyk-sink: https://github.com/TykTechnologies/tyk-sink/pull/49
