### ISSUE TITLE
Allow merging policies with multiple access rights partitions

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1783]
Currently it is not possible to mix policies with overlaping access partitions (access rights, rate limits and quotas). 

End goal is ability to specify different rate limits for different access rights. 
It should be possible to define different rate limits and quotas for different APIs or for example different paths. So both of the following scenarious should be possible: `ApiA - 100rps, ApiB - 1000rps` and `ApiA /path1 - 100rps, ApiA /path2 - 200rps` 

In order to impement it with minimal changes, and keeping basic architecture, I propose the following:  instead of extending policy object with access rights array support, I propose instead merge multiple policies. It actually can be not really merging, but more a traversing thought the list of policies, to find matching rule. In order to separately track rate limits and quotas, key names used to track it should include matched policy id. 

To make it backward compatible, so users will not loose rate limits and quotas data after the upgrade, we can add check that if multiple access rights defined in multiple policies, turn on new keys format, otherwise use old ones. 

Additionally, for better policy organization, and in oder to make it work for JWT and OpenID based APIs (when you can specify only one policy) I propose to implement "meta" policies, when you can create special policy which consist of multiple policies (similar to keys, matter of adding `apply_policies` field), and if key created with such policy, its `apply_policies` fields gets populated with "meta" policy `apply_policies` field. No need to support deeply nested scenarious, only 1 level.

**Comment by lonelycode** [comment]
To confirm, this is per-token, per-api?

**Comment by asoorm** [comment]
@lonelycode - In other words - Apply rate limits per API, per policy. So I am user X, with Policy Y. Policy Y states that API(1) has 10 rps and API(2) has 20 rps. And that is applied at the token level. 

So instead of creating a token bucket to catch all, you create a token+policy+api bucket combo and feed that instead of feeding a general bucket.

**Comment by letzya** [comment]
So this will be defined on policy def, right?

**Comment by buger** [comment]
@asoorm I updated title and description

**Comment by dencoded** [comment]
Just some thoughts to clarify what needs to be done. We need to be able to specify `rate limit` and `quotas` on three levels:

1. Per Policy (we have that piece now)
2. Per API included in policy's access rights
3. Per path for any API from policy's access rights list

As I understand that would be on a single policy level without having to create several policies and attaching them to a key.

Another thing - we will likely need some validation rules in place, i.e.:
- rate limits on API level can't be bigger than rate limit on policy level (if specified)
- rate limit on path-level can't be bigger than rate limit on API level if specified
- sum of quotas on API level should be no more than quota specified on policy level
- sum of quotas on path level should be no more than quota specified on API level

As to quota counters and leaky bucket rate limiter keys - I think creating special keys should work. I.e. we can extend key format to be `key_hash:policy_id:api_id:path`

Also, when we count requests we need to accumulate on all specified levels and check in direction from high level to lower one:
- `key_hash:policy_id`
- `key_hash:policy_id:api_id`
- `key_hash:policy_id:api_id:path`

I.e. we have policy with rate limit 1000 rps and that policy provides access to api1 and api2. Say we want to specify rate per API. We could do for api1 800 rps and for api2 300rps which both are under policy rate 1000rps but if we have traffic simultaneously to both APIs they could hit 1100 rps (800+300). Also api1 has rate limit for `/path_abc`
In case of request to `api1/path_abc` the order of checks "is it time to reply with 429" would be
- check policy `key_hash:policy_id` counter (as other APIs from access rights might exceeded it already)
- check `key_hash:policy_id:api1` counter (as requests from other paths might already exceeded it already)
- check `key_hash:policy_id:api1:/path_abc` counter

Also one more change discussed here:
4. Introduce concept of meta-policy which is policy containing group of other policies. 

I feel like this is too much for one ticket, should we create another ticket for meta-policy change? @buger @asoorm what do you think?

**Comment by buger** [comment]
@dencoded I think you a bit misunderstood initial proposal. Specifying it using single policy will cause lot of issues, since we had to completely change structure of policy object, and maintain backward compatibility with old and new policies. Even now you already can attach multiple policies to the key, and idea is to extend this support, so you can define multiple rate limits and quotas in different policies, and just specify multiple policies for the key. In this case, "meta" policy becomes quite an easy task, since if key will see policy like this, it will just inherit policies from this "meta" and that's all. I specified it in top task description, but probably not clear enough. 

Regarding key format, it definitely makes sense, but I propose making it a bit simpler. Instead of supporting hierarchy like this, we can do the following: dynamically iterate through all policies attached to the key, and find the deepest match (Global -> API -> Path), and just use this value.

Also, a quite common case when dealing with rate limits will be that total API rate limit is quite slow, and one of the paths (like status API), will have way bigger rate limit. So I think that if you specified path specific values, they should have the separate counter, and do not intersect with upper rate limits or quotas. 

Does this makes sense?

**Comment by dencoded** [comment]
@buger yep, title for this issue and underlaying conversation are a little confusing (I read mostly conversation).

another concern - having that this issue flagged as "customer request" but it is not easy to understand what was that "customer request". simple description of user flow in terms of UI in dash board would be helpful.

according to policy structure - looks like every policy in addition to quota and rate limit will have to be associated with (optionally):
- quota and rate limit per API from access rights list
- quota and rate limit per path for any API from access rights list
where do you propose to store those things?

For multiple policies per key - all policies assigned to the given key should be partitioned and constrain one of `rate`, `quota` or `acl` - every of those three should be provided no more than one of those several policies assigned.
Tbh I had hard time to understand this concept from our UI and docs until I looked into code. I assume new quotas and rate limits per API and per path will have the same logic (can be specified in partitioned [policies only)? Or no? Assuming that both things we want to add (rate and quota for APIs and API paths) belong logically to ACL - how do we  specify different things in partitioned policies if `ACL` can be checked only in one of partitioned policies?
Also, the problem I see is that partitioned policies were added initially to allow control on key level and on policy level at the same time (but overwrite only some limits on policy level), it sounds logical as key and policy have the same things to control - `rate`, `quota` or `acl`. Right now we are adding more stuff to policy like `quota` and `rates` for API and API path. If key doesn't have those things does it mean that `quota` and `rates` for API and API paths can't be part of partitioned logic?

As to key format `find the deepest match (Global -> API -> Path), and just use this value` - will it make session rate limit or quota "jumpy" back and forth? Say the same key provides access to `/path1` with 3rps and to `/path2` with 3000rps, then we get requests to `/path2` (say request number 1000 for that second) and then to `/path1` (request number 2 for that second). What is going to happen with value for rate on key session? What we are going tp sent to leaky bucket associated with that key session?

According to `separate counter, and do not intersect with upper rate limits or quotas` - it doesn't make sense to me as a potential user. If I have set rate limit for some API as 100rps I cannot understand how some paths under that API can have say x10 bigger rate. What the point to limit rate on API level then? What traffic are we limiting on API level?

huh, lots of question but we need to have answers before moving forward.

**Comment by asoorm** [comment]
@dencoded Initial ticket has morphed a bit as has been edited. This is the specific customer request: https://github.com/TykTechnologies/tyk/issues/1783#issuecomment-404192006

**Comment by dencoded** [comment]
@asoorm ok, I see. do you have any ideas about design:

- implement each of rate/quota limiting level on separate policies with applying then those several policies to key and how it is (or should it?) feet to our existing logic around partitioned policies (ACL can be specified/forced only in partitioned policy in case of attaching several policies to key)
vs
- being able to specify all rate/quota limiting levels on one policy level

**Comment by buger** [comment]
Do not really tie to "customer request" label, since our solution should be general purpose anyway. 

It can be that my ideas with policy merging is not optimal and we should embed rate limit info directly to policy, but let's try to get deep down to actual initial requirements.

Imagine the following use-case, that customer is someone like http://clearbit.com/ and have the following setup (real case):

There are 4 different APIs, sold separately. Each of those APIs has different rate limits and quotas, which depend on user subscription plan. So you can buy, small tier API1, medium tier AIP2 and etc. Free users have some limited access, only to some parts of this APIs. Also, it should be possible to properly track analytics for all cases. 

How it IMHO should work from UX side of view:
You can create policy per API, and after, based on user subscription, mix this policy together. Each individual policy should contain quotas, rate limits and access rules per API. So I will have policies like: "API1 tier1", "API1 tier2", "API2 tier1" and etc. And when you assign them to the key, you just can assign: "API1 tier1", and "API2 tier1" policies. 

As you mentioned currently we have the constraint, that multiple policies work only if partitions differ. We had to do it, due to lack of proper policy merging solution, and the point of this ticket is to eliminate this limitation, so you can mix policies however you want. But you still should be able to mix separate partitions if you want (with some sane checks, like multiple SAME partitions per SAME API not allowed). 

> According to separate counter, and do not intersect with upper rate limits or quotas - it doesn't make sense to me as a potential user. If I have set rate limit for some API as 100rps I cannot understand how some paths under that API can have say x10 bigger rate. What the point to limit rate on API level then? What traffic are we limiting on API level?

From our architecture point of view, setting separate limits per path will be tricky, so I propose to exclude this part from task definition (and you can always just create a separate API for this path if you want separate tracking). But one of the valid cases for such configuration is when your API has some status check, or similar, which should not obey the same rate limit as your API, and should have way higher limits. We can back to rate limit issue on per path rate limiting later (and maybe, in this case, it can be embedded into policy itself, to "Path-based permissions" section, and only for rate limits, and maybe with option to disable quota tracking for specified paths).

**Comment by buger** [comment]
Hopefully in the next few weeks as part of 2.8 release.

Cheers.

**Comment by ilijabojanovic** [comment]
Verified
