### ISSUE TITLE
Mapping JWT scopes to policies

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1834]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
At the moment Tyk ignores `scopes` attached to oAuth/JWT tokens, and it just forces you to use the specified fixed policy id for all keys.  Moreover, at the moment access_token data not used at all.
**What is the expected behavior?**
It should be possible to specify "scope" -> "policy" mapping in API definition, and if done so, Tyk should call oAuth [token introspection endpoint](https://www.oauth.com/oauth2-servers/token-introspection-endpoint/) to get scopes info about the token scopes, and use policy merging technique described in this task https://github.com/TykTechnologies/tyk/issues/1783#issuecomment-406580854

So you can define smth like: "users:read" -> policy1, "users:write" -> policy2, and etc.

Note that it should be possible to dynamically revoke user scopes from IDP side, and tyk should see this changes. Doing it in secure and performant way, described in oAuth.com link above:

> One way to mitigate this problem is for consumers to never cache the value beyond the expiration time of the token, which would have been returned in the “exp” parameter of the introspection response.

**Comment by letzya** [comment]
Maybe we can hold off on integrating with `/introspect` since this endpoint is important to verify if an access_token has been revoked or not when we want to be extra careful and not just trust the `exp` claim. It is also useful to get scopes when the access_token is opaque but for now, many IdPs support JWT access_token so it might be enough for releasing this feature and the extra security of `/introspect` can be achieved with a plugin.

**Comment by ilijabojanovic** [comment]
We have several issues related to this feature, i will link new issues to this task
