### ISSUE TITLE
Prepend org ID to key hash

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1872]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
At the moment, if key hashing turned on, there is no way to know its org ID without actually fetching the key. In contrary, without hashing, orgid is a first part of the key. Because of this we can't allow listing hashed keys (because we can't verify keys ownership in batch). 
**What is the expected behavior?**
We can introduce a new option, which when turned on, we append org id to the key hash in redis. 
The trick here, is to ensure how to make this change backward compatible or at least make switch less painful. 

One of the ideas: if special compatibility mode turned on, it will first tries to read hash with org id, if not found it will fallback to regular hash, and if the last one is found, it will create new org prefixed hashed record.

Additionally, we can provide a script which will enumerate through all existing keys, and will re-create key by adding orgID prefix to key name. Need to be careful, so we do not loose any data.

**Comment by lonelycode** [comment]
I assume you mean prepend / prefix the token with the org ID, not actually adding as a suffix?

In non-hashed node we enumerate keys by just scanning the api-key-{orgid}* namespace in redis with a SCAN, this guarantees we get only owned tokens back and is quite efficient.

That’s all fine, because a legacy key uses the orgid as a prefix anyway so it’s all built in.

But because we hash the whole key, the org data is lost and so we can’t enumerate anymore as we’ll get back an empty list.

Our storage driver already has a native capability to namespace all keys (for example the “api-key” is automatically added as a prefix on write and removed on read when working with the key store)

We could do something similar with namespacing the organisation, just add it on write and remove it on read so it’s transparent.

For backwards compatibility, if this feature is enabled, we just do a double read like you say.

**Comment by buger** [comment]
Yes, for sure I meant prefix.

I also realized that doing hashing with different algos can be problematic, since we will be unable to list them. But I can force it to use murmur64 for orgs.
