### ISSUE TITLE
[TT-360] Support setting quota and rate limits against oauth2 client id

### ISSUE THREAD

**Issue by amadeus-x1** [TykTechnologies/tyk#2013]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When creating access tokens against oauth2 client id, quota and rate limits apply separately to individual access tokens.

**What is the expected behavior?**
Have an option to support quotas and rate limits and client id level.

**Comment by letzya** [comment]
Really good feature. A developer can have a client_id can have a few "live" access_tokens since he is writing an app that is being tested in a few environments but essentially they are all the same client_id from the api owner perspective. The api owner doesn't care how many live tokens are out there as long as they are all using the client_id's quota.

**Comment by letzya** [comment]
Required by another user

**Comment by christtyk** [comment]
Would like this to stay open - request from multiple users

**Comment by christtyk** [comment]
bump

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap and we will ensure this is considered when we next look at this part of the code; I am closing the request here due to the age.

I will update this ticket as and when we implement something.

Thank you for supporting Tyk.
