### ISSUE TITLE
Feature request: allow middleware to terminate request handling and return response

### ISSUE THREAD

**Issue by JosephEarl** [TykTechnologies/tyk#207]
I have a backend service with an API something like:

```
/accounts/:id
/accounts/:id/preferences
```

In my Tyk middleware I'm routing `/account` to `/accounts/:id`, looking up the ID based on a token in a request header using my own web service.

If the request header doesn't contain a valid token, I'd like to stop processing the request and return an Unauthorized/Access Denied. At the moment I'm doing this by forwarding the request to an endpoint which returns the desired status code.

However ideally in the middleware I'd be given another option to instead stop all further processing by returning a response, e.g. `sampleMiddleware.ReturnResponse(response);`.

**Comment by lonelycode** [comment]
This could quite easily be done by adding  a `ReturnOverrides` struct to the `MiniRequestObject`, in [here](https://github.com/TykTechnologies/tyk/blob/develop/plugins.go#L20).

The ReturnOverrides could look like this:

```go
type ReturnOverrides struct {
    ResponseCode int
    ResponseError string
}
```
So a JS middleware plugin can set these values as part of it's return value.

Then, [before the middleware handler returns](https://github.com/TykTechnologies/tyk/blob/develop/plugins.go#L186), if the error string in the `MiniRequestObject` is not empty, and the code is not `0`, return the new code and an `errors.New(errorString)` instead of `200, nil`, this would instantly cause an error response to be returned in the [middleware processor](https://github.com/TykTechnologies/tyk/blob/develop/middleware.go#L45).

**Comment by JosephEarl** [comment]
Thanks @lonelycode will do that!

**Comment by JosephEarl** [comment]
Sorry didn't mean to close it.
