### ISSUE TITLE
Keys not Showing in Dashboard

### ISSUE THREAD

**Issue by philipbjorge** [TykTechnologies/tyk#208]
I'm working on the integration described in option 1 at: https://tyk.io/v1.9/access-control/oauth2/

Our authentication server hands back reference tokens to clients.
Before issuing the token, it makes an HTTP call to /tyk/keys/{{reference_token}} so Tyk can be used for rate limiting etc.
I've turned off key hashing because I would like to see and administer these reference tokens from the dashboard.

I can see my key in Redis and its data matches that of keys I can see. In addition, rate limiting, authorization, and analytics are working. 

However, it still doesn't show in the dashboard. The only thing that makes them show in the dashboard is to adjust their redis key so that it matches the length of keys generated through the dashboard...

For example, changing `apikey-e3c405e673e3f8f8f5b914d504a9540a` to `apikey-56d3d9de6e4da05a95000001e3ab767200e44a866cc00963a40ce39f` makes it display.

Any way to make this work?

**Comment by lonelycode** [comment]
The dashboard will only pull keys the organisation owns, s:

1. make sure you are using a dashboard user that belongs to an org
2. Make sure all APIs / Policies etc belong to that org
3. When you generate custom keys they need to be in the form orgid+key, otherwise they will not show up.
4. Do not use a superuser, or non-org user to do anything but bootstrap and pull data

There's no other way to make it work, the Dashboard only works with keys that the org that the user that is doing the requesting owns, and then only in unhashed mode.

**Comment by philipbjorge** [comment]
`3` was what I was missing which makes sense...
There'd be no way to pull that key out of Redis without the org_id in the key.

Thanks
