### ISSUE TITLE
how about the latest version performance

### ISSUE THREAD

**Issue by cmdares** [TykTechnologies/tyk#2311]
previous post
https://www.bbva.com/en/api-gateways-kong-vs-tyk/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asoorm** [comment]
The article which you refer to is quite old. Since the article, we have had 5 major releases (2.4 - 2.8), with 2.9 coming very soon. Each release has introduced significant performance optimisations allowing a higher throughput and introducing lower latency.

We have not tested Kong performance however our users suggest that both solutions are about even for simple scenarios. Every use-case is different, and depending on what the gateways need to do in a real-world more complex scenario will likely skew benchmarks. Our users tend to find the capability, extensibility and usability of Tyk a compelling Enterprise option.

Take a look at https://tyk.io/blog/performance-tuning-your-tyk-api-gateway/ if running your own benchmarks. Would be great to hear how you get on.

For reference, I did my tests on a 2-core 4gb digital ocean droplet with Redis, Upstream, Gateway, and load generation server all running on the same box. Despite resource contention, Tyk still managed to achieve 6900rps passthrough at peak with the gateway introducing ~9ms latency at the 95th %ile.
