### ISSUE TITLE
[TT-2392] - Extend the REST API to provide policy management

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#2379]
**Do you want to request a *feature* or report a *bug*?**
Feature/Enhancement

**What is the current behavior?**
Only file-based policies are supported at the moment, as described [here](https://tyk.io/docs/with-tyk-community-edition/tutorials/create-security-policy/).

**What is the expected behavior?**
It would be useful to implement an endpoint similar to the one that's used [for keys](https://tyk.io/docs/with-tyk-community-edition/tutorials/create-api-token/).

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tyk Gateway (CE)

**Comment by cajund** [comment]
Use Case #1 (GET):

After policies are loaded via the file, it is necessary to obtain the policy id so that they can be given to the identity provider. The IDP then uses these policy ids to embed them into the JWT that is sent to users of varying privileges.

Use Case #2 (PUT)

Endpoint based permissions schemas can be updated on the fly from an administrative UI is the whitelisted endpoints can be updated on the fly. The alternative would be to regenerate the policy file and reload the gateway (storing the policy -> endpoint definitions in some other manner (which would still need to be done, but using this type of endpoint would prevent reloading of the gateway service.

**Comment by swchoi727** [comment]
Would it be possible to support POST and DELETE APIs as well to create new and delete existing policies?

**Comment by matiasinsaurralde** [comment]
> Would it be possible to support POST and DELETE APIs as well to create new and delete existing policies?

It should be possible, a CRUD behavior could be implemented here

**Comment by williamokano** [comment]
At least the documentation could have been updated to warn that policies management is not possible yet through the REST API, or at least on the CE version

**Comment by williamokano** [comment]
Hi @matiasinsaurralde , could you please code review my pull request? Thanks

**Comment by christtyk** [comment]
not stale

**Comment by haoyuanli** [comment]
@christtyk Thanks for continuing the discussion here

**Comment by JavaBloxx** [comment]
Would be very useful
