### ISSUE TITLE
Apply policies to organization sessions for Organization Quotas

### ISSUE THREAD

**Issue by philipbjorge** [TykTechnologies/tyk#241]
It's my understanding that I can apply quotas to all of an organization's keys by leveraging [Organization Quotas](https://tyk.io/docs/tyk-api-gateway-v-2-0/tyk-gateway-rest-api/organisation-quotas/).

After digging through the code, it looks like these are implemented by creating "Organization Session" objects where the only thing that really matters are the quota fields. It is also my understanding from the code that it will also ignore the `apply_policy_id` field.

Our usecase:
We have a secure token service that generates tokens for clients -- A client can generate lots of valid tokens.
We are using organization quotas to apply quotas to all tokens generated for a given client.

Now imagine that we have tiered quota levels and we want to update the "silver tier" across the board to have a higher quota.
I don't think there is currently a straight forward way to do that... However if policy ids were applied to organization sessions then there would be an easy way to administer this.

What do you think?

**Comment by lonelycode** [comment]
I have mixed feelings about this - it feels like a kludge, the machinery needed to make this work would inevitably also integrate ACL and rate limits at org level if you don't approach it correctly.

You could do this manually in the middleware itself instead of using the built in policy handling, it would be the only way to not introduce spurious Redis round trips.

Performance and utility is my real concern - a policy handler just for quotas, and those policies need to be unbounded (admin level - no org ID) causes edge-case security issues of having policies applied to tokens that don't belong to an org.

It might  be easier to just track an orgs quota level and manage the keys manually.

Happy to take a look at some code if you've written something, but am reticent to merge skmething like this without some serious due consideration

**Comment by philipbjorge** [comment]
@lonelycode -- No code written, just trying to understand how Tyk can handle this usecase.

> the machinery needed to make this work would inevitably also integrate ACL and rate limits at org level if you don't approach it correctly.
As long as you only applied quotas, you wouldn't need to be concerned with ACL/rate limits correct? As I understand it, the quota values are the only thing that the org quota middleware is concerned with?

> It might be easier to just track an orgs quota level and manage the keys manually.
Can you expand on this?

**Comment by lonelycode** [comment]
>As long as you only applied quotas, you wouldn't need to be concerned with ACL/rate limits correct? As I understand it, the quota values are the only thing that the org quota middleware is concerned with?

That's what I was trying to say, you would need to replicate the policy machinery in the org middleware handler since you can't use the existing one - it's too bound in with the rest of the auth mechanism. So we're talking duplication, which I'm not fond of - we already have some in the JWT handler. You could try to hook into it, but there would be side effects that I don't feel it's worth untangling for this feature

> So have a hard-coded list of quotas I'd like to enforce?

No, you introduce a new org policy object and manage it separately - the logic that applies policies does quite a lot and is intricately tied to token sessions, whereas the org system isn't tied into this subsystem. That way you can isolate quota's only and don't muddle things - I'd extend the session object and add org_policy or something.

> It might be easier to just track an orgs quota level and manage the keys manually.

Policies do a lot, and are meant to. If you are just managing quotas, then it would be easier to just track what orgs are on what quotas and change their limits appropriately as opposed to pushing policies up the stack into org territory. 

What i'm trying to say is keep it simple, pushing policies into Org territory muddles security domains and muddles logic between regular tokens and org tokens. I'm all for the feature, just not implementing it this way.

**Comment by philipbjorge** [comment]
OK, so I believe I am following you on the org policy object stuff -- Basically, you would prefer an implementation that doesn't try and shoehorn session policies into being used for org policies. That makes sense.

It also sounds like the way for us to support our usecase today is to do the following:
 - When a client is upgraded/downgraded from our administration portal we should make the request to Tyk with an updated organization policy

Does that sound correct/feasible?

**Comment by lonelycode** [comment]
> OK, so I believe I am following you on the org policy object stuff -- Basically, you would prefer an implementation that doesn't try and shoehorn session policies into being used for org policies. That makes sense.

Yup, exactly

> When a client is upgraded/downgraded from our administration portal we should make the request to Tyk with an updated organization policy

Yes, once that mechanism is in place. It will mean creating a new Org Policy object in `tykcommon` and adding a function to the Org check middleware that checks the policy exists, retrieves it, overwrites the max values in the session object before running the quota check.

We'll need to make a call on what to do if the policy does not exist but the org has values set - my preference would be to throw a warning and then to allow the org through based on existing values (if they are unset or zeroed it would block anyway.
