### ISSUE TITLE
Service Discovery Uptime Tests don't work with Consul

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk#2422]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Currently, service discovery uptime tests don't work at all, at least when using Consul as an option.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Just use service discovery with consul in your API, and then try to add uptime tests.  it doesn't work because the Gateway doesn't load the proper settings when doing uptime tests.  For example, here's teh section for uptime tests:

![image](https://user-images.githubusercontent.com/8964621/61746962-e44e8300-ad6a-11e9-8e44-43e2d85003f2.png)

It is expecting me to set the details for the uptime tests, but it doesn't allow me to set the same parameters that I have to set when doing a regular API definition:
![image](https://user-images.githubusercontent.com/8964621/61747379-bddd1780-ad6b-11e9-9693-912eddbdbca5.png)

I don't think we are providing enough info to our uptime tests to have it work properly

**Comment by buger** [comment]
Well, usually when SD is used, it is responsible for health checks. This is the main reason why this option is disabled.

**Comment by sedkis** [comment]
So when used with Tyk, do we need to use a very small cache timeout?

**Comment by buger** [comment]
Makes sense

**Comment by lonelycode** [comment]
The service discovery in uptime tests setting has a fixed object format, unlike the one for api definition where you can configure the parser quite flexibly.

Basically for uptime tests you need to provide a tyk-specific object on an endpoint and just tell the system how to get that object. 

This is because uptime tests can do more than ping, they can send full blown test requests with payloads and parameters.
