### ISSUE TITLE
tyk does not transform Location and Link headers

### ISSUE THREAD

**Issue by bboozzoo** [TykTechnologies/tyk#250]
Services commonly add `Location` or `Link` headers to direct the client to some resource. It seems that Tyk does not transform the headers to replace the URI prefix from `proxy.target_url` with `proxy.listen_path`.

API configuration:
```
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/deployments/",
        "target_url": "http://<some-host>:8080/api/0.0.1/",
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": null,
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "port_data_path": "",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 0,
            "endpoint_returns_list": false
        }
    }
```
Example:
```
# request:
curl -i -X POST -H "Content-Type: application/json" -d '{ .... }' http://localhost:9080/deployments/images

# response:
HTTP/1.1 201 Created
Connection: close
Content-Length: 281
Content-Type: application/json
Date: Thu, 28 Apr 2016 08:07:44 GMT
Location: /api/0.0.1/images/f5ae258e-6df4-4253-bf21-1759d0412e3b
X-Ratelimit-Limit: 0
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 0
{ ... } 
```

I would expect to see:
```
...
Location: /deployments/images/f5ae258e-6df4-4253-bf21-1759d0412e3b
...
```

**Comment by kjaskiewiczz** [comment]
I would suggest two possible solution:

1. Modify `HeaderInjector` response processor and change its name to HeaderTransorm (leave "header_injector" pointing to new HeaderTransform for backward compatibility).
2. Add new response processor - "header_transform": HeaderTransform{}.

In both cases HeaderTransform need to be able to modify header fields (like changing paths in `Link` and `Location` headers) according to its configuration (options).

I could send pull request with one of this solutions implemented, but I need to know which one is preferable.

**Comment by lonelycode** [comment]
I wouldn't modify the response processors, they need to be manually invoked by the API Definition as middleware. 

Instead I would look at an API Definition object-level setting, or a conf setting (even easier) that handles this rewrite all the time as a standard, always-on, response middleware processor.

So you just create a new response middleware, as you say, and call it something like `ResponseProxyHeaderCleanup` and then ensure it gets invoked on all requests instead of just registered response handler (before the chain check [here](https://github.com/TykTechnologies/tyk/blob/master/response_middleware.go#L30).

**Comment by kjaskiewiczz** [comment]
https://github.com/TykTechnologies/tyk/pull/255
