### ISSUE TITLE
Redis: Add prefix to each Tyk keys

### ISSUE THREAD

**Issue by yasseur1007** [TykTechnologies/tyk#259]
Hi,
Would it be possible to add a configuration "key_prefix" on redis section to tell Tyk to namespace
all keys by "key_prefix" + key.

The aim, at the end is to be able to share the same redis database with another application and to be sure that keys are not conflicting. (e.g 2 tyks that use the same redis db, but not on the same tyk cluster)

**Comment by lonelycode** [comment]
tyk already orefixes all of its keys. It's unlikely we'll make this configurable.

**Comment by yasseur1007** [comment]
I know that keys are already prefixed but as i said i want to add a custom prefix in addition to the tyk prefix. imagine you have two different tyks, we don't want them to use the same keys.

**Comment by yasseur1007** [comment]
By doing that you force tyk devs to use a dedicated redis database each time. As you probably know, redis databases are not infinite (16 most of the time).

**Comment by lonelycode** [comment]
Is that your use case? Multiple Tyk gateways using the same DB but no key crossover?

**Comment by yasseur1007** [comment]
Exactly:
I use kubernetes for microservices. Each micro service is on a POD.
On the same POD we want to embed a little Tyk (for responsability concern and migrations /rollbacks of configs etc...)
The problem is that we have to much services and since tyk do not allow custom key prefix if have to dedicate a hole redis db for each tyk.

But if you think this is not a good idea to embed a little tyk with each services tell me.

**Comment by lonelycode** [comment]
Is there a reason they can't share a DB, after all, that's what the access control section of the token object is for?

**Comment by yasseur1007** [comment]
For my implementation, Each tyk has to be completely isolated. Each services has the responsibility on itself and not more.
So, I don't know... if i authenticate using the same JWT on the two tyks will it have a conflict on redis keys?

**Comment by lonelycode** [comment]
yes it probably would. So this JWT identity can't have a policy that allows access to all the services? They need to auth for each service independently?

**Comment by yasseur1007** [comment]
> Hummm sorry it wasn't a good example because in my case we have to auth for each service  independently. (The secret is different)

In fact i don't know all redis keys used by tyk but yes on the JWT we inject policy claim that may be the same between each services. But that behaves not the same way on each service.

**Comment by victorboissiere** [comment]
We suffer from the same issue. Having prefixes would bring down costs. We use what we call feature branches which are completely fresh dedicated environments deployed in Kubernetes. We though about using a single staging managed Redis instance in AWS and connecting all Tyk instances from these environments to the same Redis instance but without prefixes, it won't be possible.
We're thinking about deploying a single Redis as a pod in each feature branch but it will increase cost drastically. We're considering dropping Tyk as a viable solution for our needs because of this. Would it be possible to re-open this issue?
Do you have guidelines on how we could contribute to implementing such a feature?
