### ISSUE TITLE
Nonce failed error message on Tyk Startup

### ISSUE THREAD

**Issue by alexraju** [TykTechnologies/tyk#260]
Getting Nonce failed error message on Tyk Startup in Dashboard log

Nonce failed! Node:d1680fa1-12db-4f7a-57e4-d6e41c5b417f Nonce was:XXXXXXX Should be: YYYYYYY"

How critical is this issue and how can I resolve this issue?

**Comment by lonelycode** [comment]
It's only critical of your Tyk APIs aren't loading and this is a cold start. Because if that's the case then your gateway is not starting and can't pull its API definitions.

Start your dashboard service, with license, first, and then start your gateway. 

This is only really meaningful if you include the gateway log output from a cold start

**Comment by kohrVid** [comment]
Hi Alex,

Did Martin's suggestion help with this problem back in June? If so, would it be all right if we closed this issue?

Kind regards,
Jess

**Comment by lonelycode** [comment]
This issue was resolved in the v2.3 release of Tyk - nonces are no longer used.
