### ISSUE TITLE
[TT-2381] - Detailed error analytics

### ISSUE THREAD

**Issue by Zavierazo** [TykTechnologies/tyk#2615]
**Is your feature request related to a problem? Please describe.**
Be able to differentiate in the analytics the errors returned by tyk vs backend(Target URL)

Also sometimes tyk reuse the same http code for multiple different errors.(Example Overquota & Access disallowed is 403 http error)

**Describe the solution you'd like**
Add new field on tyk-pump analytics data with a extended message with detail about the errors:
Tyk errors:
- Key is inactive, please renew
- Key has expired, please renew
- Not found
- Quota exceeded
- Authorization field missing
- Rate limit exceeded
- Access to this API has been disallowed
- ...
Backend errors:
- Backend error

This feature requires a change on tyk-gateway and tyk-pump logic

**Describe alternatives you've considered**
Another alternative can be a error message field who is only populated when tyk have an error with the message error.

**Additional context**
This is very useful for non-technical people, since at a glance in the analytics you can see the reason why the client is failing.

**Comment by christtyk** [comment]
Would like to keep open - SLA client request

**Comment by christtyk** [comment]
bump

**Comment by andyo-tyk** [comment]
Hi @Zavierazo,
Sorry for the lack of update here in Github, but as you're hopefully aware we are looking after this request and others elsewhere, with the support of your Account Manager.
I'd like to close the issue here, as we're tracking elsewhere and looking to streamline our communication with you.
If you'd prefer that I re-open the ticket, please just comment and I can do so.
Thanks for your support.
