### ISSUE TITLE
Tyk Gateway system time how to keep the consistency of each node

### ISSUE THREAD

**Issue by swan-go** [TykTechnologies/tyk#269]
If the tyk Gateway cluster pattern, tyk Gateway system time how to keep the consistency of each node, because the rate limits need to keep every time high consistency at each node, thanks

**Comment by lonelycode** [comment]
Rate limiting is done in redis, so it's automatically in sync across nodes

**Comment by swan-go** [comment]
From tyk gateway source code:
`
log.Debug("keyName is: ", keyName)
now := time.Now()
log.Debug("Now is:", now)
...
ZADD.Cmd = "ZADD"
ZADD.Args = []interface{}{keyName, now.UnixNano(), strconv.Itoa(int(now.UnixNano()))}
`

From tyk gateway source code to see, if time is 09:00:01 at node1, and the other node2 time is 09:00:10, 
how can you ensure the cluster environment tyk gateway correct speed limit?

**Comment by lonelycode** [comment]
Well, keeping the clocks in sync across nodes is up to you (ntpd is useful), and secondly the log output only reflects a part of the actual rate limit operation. That output shows a request being logged to a sorted set.

The way the rate limiter works (high-level) is with a sorted list in redis. Every request is asynchronously added to the bottom of the list with the time stamp epoch as an index. In the same transaction, the top X number of entries that fall between the rate limit period are removed and counted from the top.

If the count is larger than the limit per period, then the request is blocked. Since other requests keep adding to the bottom, the rate limit is rolling and so is accurate at the time of the request for each request no matter where it landed.

**Comment by swan-go** [comment]
Ok, thanks, may be use ntpd service to solve it.
