### ISSUE TITLE
storage_expiration_time not working correctly

### ISSUE THREAD

**Issue by maciejwojciechowski** [TykTechnologies/tyk#2805]
**Branch/Environment/Version**
- Branch/Version: tested on release-2.9
- Environment: on prem

**Describe the bug**
It seems the record in redis is stored longer than time defined by storage_expiration_time
This is not 100%

**Reproduction steps**

Set this is tyk.conf
```
enable_analytics: true,
analytics_config.storage_expiration_time: 15
```
1. Add api and key
2. Switch off pump so the record from redis is not processed
2. Send 1 request to that api
3. Observe redis record and its TTL

**Actual behavior**
Sometimes the TTL is counted 2 times so the record resides in redis longer than expected

**Expected behavior**
When TTL goes down to 0 redis record should be removed.

**Screenshots/Video**
![redis_ttl_3](https://user-images.githubusercontent.com/39672152/72518633-0f1b1f00-3856-11ea-9eb8-a7d4e8afd011.gif)

**Configuration (tyk config file):**

[tyk_conf.txt](https://github.com/TykTechnologies/tyk/files/4070769/tyk_conf.txt)

**Comment by asoorm** [comment]
```
func (r *RedisPurger) PurgeCache() {
	expireAfter := config.Global().AnalyticsConfig.StorageExpirationTime
	if expireAfter == 0 {
		expireAfter = 60 // 1 minute
	}	exp, _ := r.Store.GetExp(analyticsKeyName)
	if exp <= 0 {
		r.Store.SetExp(analyticsKeyName, int64(expireAfter))
	}
}
```

This looks wrong. `if exp <= 0`
-2 means the key doesnt exist. - This happens when the expiry has been reached...
-1 means the key exists but has no expire. 0 means it will expire in 0 seconds, but the key still exists. 

So before it gets opportunity to actually delete the key (arriving at -2), it extends the expiry to `expireAfter`.

@buger the purger should only set the expiry on the key `if exp == -1`.

**Comment by ilijabojanovic** [comment]
Verified and safe for merge @buger
