### ISSUE TITLE
Virtual paths, conditional aggregation and service discovery

### ISSUE THREAD

**Issue by lmlynik** [TykTechnologies/tyk#289]
Hello,

We are currently evaluating Tyk. Looks very impressive for our use cases, but there are couple of little things we need to iron out before we will use it.

One of our main use cases is API aggregation for clients.
The documentation contains examples to do simple batch aggregation for static URLs. Is there a way to store these urls somewhere and load them via javascript into the Virtual Path code? Maybe even use consul for service registry.

Other use case is more of a design question:
Should a gateway contain conditional calls - meaning that if call service-A will return an error we should not call service-B.

**Comment by lonelycode** [comment]
Hi @lmlynik thanks for considering Tyk - this kind of question would probably be better placed on our [community forum](https://community.tyk.io).

To answer your questions: 

> The documentation contains examples to do simple batch aggregation for static URLs. Is there a way to store these urls somewhere and load them via javascript into the Virtual Path code? Maybe even use consul for service registry.

Virtual Paths are interpreted at least once by the gateway when the API Definition is loaded into memory (in order to pre-warm the script for faster execution). So you could add an init method to the first Virtual Path to be loaded (longest first) and call it outside of the method to setup any kinds of globals for that virtual path. IIRC Virtual Paths for a single API share an ECMAScript environment, so globals / services could be shared.

> Should a gateway contain conditional calls - meaning that if call service-A will return an error we should not call service-B.

That's a good point, currently batches execute regardless of return code, you don't need to use the batch caller and could always use the built-in HTTP Request (`TykMakeHttpRequest`) method to compose your chains conditionally.

**Comment by lmlynik** [comment]
Thanks @lonelycode for the rapid response.

> Virtual Paths are interpreted at least once by the gateway when the API Definition is loaded into memory (in order to pre-warm the script for faster execution). So you could add an init method to the first Virtual Path to be loaded (longest first) and call it outside of the method to setup any kinds of globals for that virtual path. IIRC Virtual Paths for a single API share an ECMAScript environment, so globals / services could be shared.

Is there a way to dynamically register our internal endpoints to Tyk and have the virtual endpoints read that data.
I was thinking even of introducing a virtual endpoint which would register a service globally in the ECMAScript environment, but as you mentioned the scripts are parsed just once during startup.

Is there any way to the virtual endpoint js code to read from some dynamic datasource?

**Comment by lonelycode** [comment]
> Is there any way to the virtual endpoint js code to read from some dynamic datasource?

You have the Http request mechanism, so you could have an external service provide that data on init to the JS by pulling i ton first parse, and then flush it based on some timestamp delta as requests are handled. But apart from that, the environment is pretty sealed up.

**Comment by kohrVid** [comment]
Hi Łukasz,

Did the suggestion Martin gave back in August help with this at all? If so, would it be all right if we closed this issue?

Kind regards,
Jess

**Comment by lmlynik** [comment]
Yes, @kohrVid , we can close this
