### ISSUE TITLE
Feature request: Support Auth0's client credentials grant flow

### ISSUE THREAD

**Issue by ryanwalls** [TykTechnologies/tyk#299]
Auth0 now has the capability to handle the client credentials grant flow.  See https://auth0.com/docs/api-auth/grant/client-credentials.

The token that is generated has a different format for claims than the standard user claim.  

Claims look like this:

```
{
  "iss": "https://3dsim.auth0.com/",
  "sub": "PV2AvGcMjOFErV6QposKnfrUdt8yPuHI@clients",
  "aud": "https://workflow-qa.3dsim.com",
  "exp": 1474728993,
  "iat": 1474642593,
  "scope": "write:workflows read:workflows"
}
```

So to support this, I imagine Tyk would need to recognize that the client is actually sent in the `sub` field instead of the `aud` field.

**Comment by ryanwalls** [comment]
Started a community discussion as well, in case that would be a better place to discuss.  https://community.tyk.io/t/support-auth0-client-credentials-flow/1037

Would be nice to track the issue through github as well... but understand every org has a different flow for issues. :)

**Comment by lonelycode** [comment]
Usually bugs go into GitHub on the repo and feature requests go to the forum. We will track bugs here if they are relevant to the underlying repo.

We don't use GitHub for feature tracking because we have so many repositories, and touch points for bugs / issues / discussions etc (GitHub, forum, support desk, direct), so everything goes via our trello roadmap (public) where we move features into versions and into development, we'll close off stuff here after a release, but it's not guaranteed to make it into a build cycle unless we see demand.

**Comment by ryanwalls** [comment]
@lonelycode Got it.  Makes sense.  Feel free to close this issue then and I'll just track the forum discussion.
