### ISSUE TITLE
[TT-1997] - CORS: Use regex pattern for allowed domains

### ISSUE THREAD

**Issue by FilmKnurd** [TykTechnologies/tyk#3167]
**Is your feature request related to a problem? Please describe.**
We have a dynamic infrastructure with application servers being pun up when pull requests are opened. The CORS configuration is difficult to setup because each allowed domain has to be added explicitly. 

**Describe the solution you'd like**
Ideally, we could specify a pattern for allowed domains. If a request matches the pattern, then return the origin domain as allowed in the CORS header.

**Describe alternatives you've considered**
We tried using virtual endpoints to return the allowed domain header, but that ended up being a little unwieldy. In the end, we opted to allow "*" domain.

**Comment by andyo-tyk** [comment]
Thanks for this suggestion.

We support wildcards in the allowed origin domains (e.g. `*.foo.com`) so that you don't have to allow all domains by setting `allowed_origins: ["*"]`.

There's no plan at this stage to add regex pattern matching to this function, though when next we look at this area of the code we will keep the suggestion in mind.

Thank you for supporting Tyk!
