### ISSUE TITLE
[TD-220] musl image variants

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3251]
**Is your feature request related to a problem? Please describe.**

Offer musl variants of the Docker images, e.g. Alpine Linux. This helps DevOps to reduce resource requirements for wide scale deployments.

**Describe the solution you'd like**

Offer -alpine image tags.

**Comment by alephnull** [comment]
We depend on libc and do not have the capacity to officially certify musl at this point. 

Restricting the discussion to gateway, since go plugins preclude fully static builds that would meaningfully reduce the attack surface, this tradeoff is unsatisfying but I do not see a way to change the balance.
