### ISSUE TITLE
How can I enable rate limiting?

### ISSUE THREAD

**Issue by idbeta** [TykTechnologies/tyk#3437]
**Branch/Environment/Version**
- Branch/Version: 3.1.1
- Environment: ubuntu

**Describe the bug**
How can I enable rate limiting?

I create an api like this
```
curl -v -H "x-tyk-authorization: 352d20ee67be67f6340b4c0605b044b7" -s \
  -H "Content-Type: application/json" \
  -X POST \
  -d '{
    "name": "My API",
    "slug": "my-api",
    "api_id": "1",
    "auth": {
      "auth_header_name": "Authorization"
    },
    "version_data": {
      "not_versioned": true,
      "versions": {
        "Default": {
          "name": "Default",
          "expires": "3000-01-02 15:04",
          "use_extended_paths": true
        }
      }
    },
    "proxy": {
      "listen_path": "/myapi",
      "target_url": "http://127.0.0.1:7000/",
      "strip_listen_path": true
    },
    "disable_rate_limit": false,
    "global_rate_limit": {
      "rate": 1000,
      "per": 1
    },
    "active": true
}' http://localhost:8080/tyk/apis/ | python -mjson.tool
```

but when I access the api, it look like the `rate_limit` is invalid:
```
curl -H "Authorization: 1f8890fc043104f57ad4bcfe31e27eef0" http://127.0.0.1:8080/myapi -i
HTTP/1.1 200 OK
Content-Length: 21
Content-Type: text/plain
Date: Mon, 04 Jan 2021 10:07:41 GMT
Server: nginx
X-Ratelimit-Limit: -1
X-Ratelimit-Remaining: -1
X-Ratelimit-Reset: 1609754910
```

**Comment by buger** [comment]
Hi! 

There is some naming conflict here, due to historical reason. 
In Tyk there are two way to limiting request rate: Rate limit and Quota. 

Think about Rate limit as a security features, and quota as a billing feature. 
Quota mechanism i what is usually used by majority of APIs, and in majority of cases "X-Ratelimit" headers actually contain quota info. So in your case global rate limit should work as expected, as security, but in order to have X-Rate-limit you need to use quota mechanism. 

In order to have non-global quota or rate-limit require having you some unique user identifier, which will be used to store this "counters". But in this case API will need to be non keyless. 

If you need to have it for keyless API you can do a few tricks.
First if writing custom auth middleware, which for example use IP address as user key https://tyk.io/ip-rate-limiter-middleware/
Another option will be using https://tyk.io/docs/advanced-configuration/transform-traffic/looping/, and essentially you will have two APIs. Your current one will be turned to Auth token API, and on top of it you will have keyless API which will forward traffic to your "real" api using looping. Then you create a "global" API key with limits you want, and embed it as global header, so your "internal" auth API will know about limits. 

Hope it makes sense!
