### ISSUE TITLE
Python plugins: 

### ISSUE THREAD

**Issue by tobiasb** [TykTechnologies/tyk#3468]
**Branch/Environment/Version**
- Branch/Version: 3.0.1
- Environment: On-prem

**Describe the bug**
I have a rich python plugin and I’m puzzled about what I’m seeing.
In the constructor of the middleware I initialize a `threading.Thread` in the `target` (method) of which I have a simple loop:

```
while True:
  logger.info(“thread alive…”)
  time.sleep(1)
```

I would expect a continuous stream of `thread alive…` messages in my log. However what I am seeing is a single “thread alive…” message in the logs and then silence. Interestingly, if I send the occasional request through Tyk, I see additional `thread alive…` messages in my logs after that. Is there anything in the Tyk implementation that would explain this strange behavior I’m seeing with threading?

**Comment by buger** [comment]
cc @matiasinsaurralde

**Comment by buger** [comment]
We embed Python using specific C api, maybe it has some threading limitations.

But threading will not give you multi cpu support anyway, because of GIL https://stackoverflow.com/questions/29947994/threading-in-python-using-multiple-cores

I would rather investigate asyncio approach.

And if you need multi core experience it will require multi process  or this lib https://docs.python.org/3/library/multiprocessing.html. But since Tyk not directly runs Python binary, you would need to go with converting your api to be a separate “coprocess”, and then it should work.

**Comment by tobiasb** [comment]
Thank you @buger for your quick response. I understand the behavior a little better now.

> And if you need multi core experience it will require multi process or this lib

Before I dive into it, would that be the best approach if all I want is some background thread doing periodic work? All I'd like to do is have a loop in the background refresh an access token every 5 minutes or so and ideally I'd like to do this inside my Tyk plugin. I thought about having a cron job on the machine do this and store the access token somewhere for the Tyk plugin to access but I'd like to avoid that because it makes testing difficult and it would add another read to the request processing. I've also thought about doing the access token refresh as part of a request but then it would add latency to that request and also I'd have to deal with parallel request and possible the token getting refreshed more than once at the same time, again I'd like to avoid that.

What would be the easiest way to add some parallel "worker" that is to share data with my Tyk middleware (the access token)?

**Comment by buger** [comment]
Just talked with the team. 
There is no way to run some async jobs in current Python integration. 
Embedding this logic inside the request, as you described, with some mutex and caching is one option.

Another option is running your plugin as a separate process, and Tyk will communicate with it using gRPC channel. In Tyk it called gRPC plugins https://tyk.io/docs/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin/.

And final option is using Golang plugins https://tyk.io/docs/plugins/supported-languages/golang/, since it is native to Tyk, runs almost without overhead and have no any limitations.

**Comment by tobiasb** [comment]
Thank you
