### ISSUE TITLE
Protect APIs with client certificates

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#357]
As a user I should be able to protect my application with an approved set of client certificates:

For Auth:

- The client cert should be aligned with a token or a policy so that we can set rate limits - this may require a generating an internal representation of the token using: OrgID + hash(certificate) to store the metadata
- The certificates should be encrypted or protected in some way while at rest in redis
- When a request comes in, presented client cert should be used to identify the underlying token / identity to apply rate limits
- Should follow the same rules as a standard auth middleware (i.e. support chaining)

For management:

- I should be able to add a CA Cert to the gateway using the REST API, it should reply with a key ID I can use to manage this certificate
- I should be able to look up a certificate's session data by just querying using the certificate itself

**Comment by buger** [comment]
I made some research, and it does not look that scary. 
Actually, it can work very similar to how "Auth token" works. 

First of all, single gateway probably can't handle both api's with and without Mutual TLS auth, because gateway instance should be configured in a special way. If a customer will want some API's to use non-Mutual TLS auth, they should have multiple gateways with different tags.

We do not have to create a special mapping between certificate and token, instead, we will use certificate `CommonName` field to store token information - it is a popular approach for mutual TLS.

The certificate itself consist of 2 parts public and private. For our use-case, to check client, we need only its public part. But we should still give the private key to the user. I would propose do not store it at all in our system, and return it only once when we generated cert, in API response. In the case of UI it will look similar to how Amazon do: once you requested key, it shows prompt which give you chance to download the key, if you close it, you have to issue a new key.

Certificate public information will be stored similar to basic auth, in key data: "cert": "...", and we do not need to encrypt it anyhow. 

Well, to be clear, since this certificate bind to API token, we can easily revoke it, so maybe it make no sense to remove private data and store it together with private one. Actually, we can make it configurable. But for sure hiding private key will require way more business logic and UI. We can go with some "salt" encryption as well (for example use "secret" as salt)

Here is the initial plan:

## Gateway
We should add an option on gateway level to enable mutual auth. Once enabled our TLS configuration should include following options:

```
ClientAuth: tls.RequireAndVerifyClientCert,
ClientCAs: clientCertPool,
```
Were `clientCertPool` is:
```
clientCertPool := x509.NewCertPool()
clientCertPool.AppendCertsFromPEM(clientCACert)
```
It will also mean that we need to scan for all active API tokens, extract Cert data from them, and add to our certificate pool.

Middleware which will be used for auth will extract token data from certificate `CommonName` field, using `(http.Request).TLS` variable, and after we have token will act exactly same way as "Auth token" middleware. 

To create keys we will define new API, similar to how we handle basic auth, and as mentioned above it should return both public and private info. As an alternative, it can be included into regular "key" create method.

Worth noticing that if key is expired or removed, we should delete it from ca pool as well. 

## Dashboard

We should have a checkbox on Key creation page, called "Generate certificate", and once the key is created, it should be possible to download public (and maybe private) certificate parts.

API should have new authentification method called "Mutual TLS", with no configuration options.

## Portal
If the key has certificate, the developer should be able to download it.

## Links

http://www.bite-code.com/2015/06/25/tls-mutual-auth-in-golang/
http://www.levigross.com/2015/11/21/mutual-tls-authentication-in-go/
https://blog.codeship.com/how-to-set-up-mutual-tls-authentication/

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Client Certificate Authentication support](https://trello.com/c/2868N73N/417-client-certificate-authentication-support)

**Comment by steve-jansen** [comment]
@buger Do you envision Tyk verifying the the client cert against any Certificate Revocation List (CRL) or Online Certificate Status Protocol (OCSP) listed in the cert?  

Here's an example from the google.com server cert:

![Example of OCSP and CRL attributes in the google.com x509 cert](https://user-images.githubusercontent.com/3165077/29788191-b8fbd3bc-8bff-11e7-9611-a3dfd273c899.png)

Think of revocation as a killswitch for an otherwise valid cert: a device has been compromised, an employee has left a company, etc.

This may be a non-issue with your intended use case if you assume authorization would be revoked elsewhere in the Tyk control plane.   Nevertheless, you may want to highlight if CRL/OCSP isn't honored.  This part of x509 is often overlooked in early implementations, so figured I'd help to highlight it early in your design process.

**Comment by ilijabojanovic** [comment]
@lonelycode @buger @lghiur @nickReyn 
If we start gateway in http mode without ssl enabled, we should Hide Certificates section on dashboard?

**Comment by lonelycode** [comment]
I’d rather not add that kind of complexity. MTLS feature should grow an error though

**Comment by ilijabojanovic** [comment]
Verified and ready for merge
