### ISSUE TITLE
Does Tyk supports east west traffic between microservices and does it integrate with service meshes such as istio, linkerd and service mesh manager such as meshery?

### ISSUE THREAD

**Issue by nathanawmk** [TykTechnologies/tyk#3676]
Hello! Does Tyk supports east west traffic between microservices and does it integrate with service meshes such as istio, linkerd and service mesh manager such as meshery?

**Comment by joshblakeley** [comment]
Hey Thanks for the question.

Generally the best approach for Tyk and service meshes taken by our users is as a drop in replacement for the ingress gateway at the cluster edges when a need is there for a more API management focussed approach instead of an edge proxy one. i.e. more plugin extensibility, OOTBN middleware and authN/Z support/ developer portal/ Enterprise SSO support etc

Primary we are used with Istio or with Openshift Service Mesh but LinkerD approach would be similar.

**Comment by agata-wit** [comment]
@nathanawmk I will close this issue. In case you have any follow up questions regarding this, please just reopen and we'll continue the discussion here.
