### ISSUE TITLE
When api is created via tyk gateway api, api_id is empty

### ISSUE THREAD

**Issue by cuttingedge1109** [TykTechnologies/tyk#4004]
**Branch/Environment/Version**
- Branch/Version: stable4.0.0
- Environment: On-prem

**Describe the bug**
When a new API is created by gateway api `/tyk/apis`, `api_id` field is not generated by tyk gateway. It seems api json file is generated with the name `${api_id}.json` in /opt/tyk-gateway/apps` dir. But because of empty `api_id`, only one file - `.json` file is always generated for any api creation. It means I can only create one API because the latter api is overwriting `.json` file with its spec.

I can pass `api_id` in the POST request data when create a new api but `api_id` should be generated by gateway uniquely, i think.

**Reproduction steps**
Create a new api without `api_id` field in POST request data.

**Expected behavior**
`api_id` should be generated by api_gateway and it should be returned as response data.

**Configuration (tyk config file):**
Used default config for on-premise tyk-gateway.

**Comment by lghiur** [comment]
@cuttingedge1109 this is not actually a bug, since this is the way it was built. The expectation is that, in the OSS GW, the 'api_id' is provided in request payload, and users store internally a mechanism for generating these.

We do the same in our projects where we use the GW (like tyk-operator or Dashboard).

Thanks for raising this up !

**Comment by cuttingedge1109** [comment]
Thank you @lghiur
