### ISSUE TITLE
Is it possible to reuse response field to othe graphql datasource instead of REST DataSources

### ISSUE THREAD

**Issue by paptimuslun** [TykTechnologies/tyk#4009]
I have just read the web site and know that I can reuse the response field something like {{.object.id}}
but I can only founs the example for passing it into other RESTful datasource, how about graphQL datasource?

**Comment by agata-wit** [comment]
Hi @paptimuslun, thanks for reaching out!
This is a very good question and you are right - it could be explained better in the docs, which I will make sure we do. But let's get to the point!

Using a response field value from one datasource as part of an input to a GraphQL datasource is possible, albeit not straightforward right now. We will be working on making this more user-friendly.

Let's assume we have a REST datasource that returns information about companies. Something like this:
`     {
      "id": "4",
      "longname": "Amazon.com Inc.",
      "address": "440 Terry Avenue North Seattle, WA 98109 USA",
      "countryOfRegistration": "US",
      "shortname": "Amazon"
     }`

Now I want to use `"countryOfRegistration"` value in [trevorblades](https://countries.trevorblades.com/) to get info like name, capital, currency, etc.

Here's how my schema would look like:
type Query {
  **getCompanies: [Company]**
}

type Company {
  id: ID
  longname: String
  shortname: String
  address: String
  countryOfRegistration: String
  **countryInfo: Country**
}

type Country {
  code: ID!
  name: String!
  capital: String
  currency: String
  emoji: String!
}

I need 2 datasources now:

1.  `getCompanies` will be pointing to my REST with a simple GET method. In API definition I'd see this:
{
            "kind": "REST",
            "name": "getCompanies",
            "internal": false,
            "root_fields": [
              {
                "type": "Query",
                "fields": [
                  "getCompanies"
                ]
              }
            ],
            "config": {
              "url": "http://localhost:3004/companies",
              "method": "GET",
              "body": "",
              "headers": {},
              "default_type_name": "Company"
            }
          }
2. `countryInfo` needs countryOfRegistration as a parameter to get information about a specific country from trevorblades. I will actually configure trevorblades as a REST in order to pass it:
{
            "kind": "REST",
            "name": "getCountryInfo",
            "internal": false,
            "root_fields": [
              {
                "type": "Company",
                "fields": [
                  "countryInfo"
                ]
              }
            ],
            "config": {
              "url": "https://countries.trevorblades.com/",
              "method": "POST",
              "body": "{\n \"query\":\"query($countryCode: ID!) {country(code: $countryCode) {name currency emoji  } }\",\n \"variables\":{\n \"countryCode\": \"{{.object.countryOfRegistration}}\"\n }\n}",
              "headers": {
                "Content-Type": "application/json"
              },
              "default_type_name": "Country"
            }
          }

So in the body section of my datasource config I am writing an explicit query I want to post in trevorblades and I am using countryOfRegistration as a variable in it. That countryOfRegistration comes from my first datasource.

This is not the greatest user experience, we are aware of that, but it is possible to get it working.

It is also something we have in the backlog to make better. No exact dates yet but we're aiming for an improvement still in 2022.
Let me know if you have more questions or if you want me to clarify something more about this.
