### ISSUE TITLE
Continue #4559 - different un authorized response in new TYK version

### ISSUE THREAD

**Issue by DavidTal** [TykTechnologies/tyk#4761]
Hello, 

In continue to the #4559 discussion, 
I have noticed that there are different un authorized responses between versions v2.5.4 & v4.0.3.

v2.5.4: 
   "error": "Key not authorised"

v4.0.3: 
 "error": "Access to this API has been disallowed"

From the code investigation I notices that the v2.5.4 message does not appear in the code anymore. It belonged to interface: AuthorisationHandler
which in v4.0.3 does no exist. It was replaced with: 
SessionHandler interface.

Could you please confirm that the above explains the difference?

**Comment by andyo-tyk** [comment]
Hi @DavidTal,

As @buger said in #4559, v2.5.4 is a very old version that has not been supported for a few years at least and receives no bug fixes or new capabilities. I strongly recommend you look to upgrade to the 4.0.x branch.

Changes in error log messages can be expected as a product evolves and, as you've identified, this message changed between versions.

If you're expecting an error from your tests or couplings, I would suggest that a more forward-compatible way is to check for the error message payload structure, rather than the contents of the message itself.

We aim to keep these compatible, but it's inevitable some messages will change over time.

Thank you for your understanding and for choosing Tyk!
