### ISSUE TITLE
Service discovery keep header

### ISSUE THREAD

**Issue by david972** [TykTechnologies/tyk#4811]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to keep header request during service discovery call
By this the discovery service can change its response according to the headers

**Describe the solution you'd like**
By adding a field like this proxy.service_discovery.keep_headers

**Comment by david972** [comment]
Does not seem interesting to you

**Comment by buger** [comment]
Hello! Sorry for delay, missed your ticket. 
Can you provide better example, maybe with some exising service discovery tool? I'm not sure what you men by "keeping" headers. 
Maybe you meant ability to set some custom headers?

Thanks!

**Comment by david972** [comment]
Let's say we define this api
```json
{
    "name": "time",
    "slug": "time",
    "api_id": "time",
    "org_id": "1",
    "use_keyless": true,
    "auth": {
      "auth_header_name": "Authorization"
    },
    "definition": {
      "location": "header",
      "key": "x-api-version"
    },
    "version_data": {
      "not_versioned": true,
      "versions": {
        "Default": {
          "name": "Default",
          "use_extended_paths": true
        }
      }
    },
    "proxy": {
      "listen_path": "/api/time/",
      "strip_listen_path": true,
      "preserve_host_header": true,
      "service_discovery": {
          "use_discovery_service": true,
          "query_endpoint": "http://discovery.tyk.svc.cluster.local:8080/api/discover/time",
          "use_nested_query": false,
          "parent_data_path": "host",
          "use_target_list": false,
          "cache_timeout": 10
        }
    },
    "active": true
}
```

then we do this request to the endpoint `/api/time`
```sh
curl -H 'Authorization: xxxxx' -H 'scope: premium' -v 'https://tyk-gw.example.com/api/time/test'
```

by keep the header for calling the service discovery endpoint
we could manage the response.

Hope it's clearer

**Comment by asoorm** [comment]
I am trying to better understand your use-case. Because it feels like 2 different concepts might be being mixed.

> It would be great to be able to keep header request during service discovery call

This is the part that is a little confusing for me.

Service Discovery is intended to enable Tyk to discover how to route your API to the upstream. **You** do not make any service discovery calls, Tyk does this automatically as per the API Definition, and the `query_endpoint ` is responsible for returning a list of upstreams to proxy to.

When you send a CURL request to an API managed by Tyk with the header `-H 'scope: premium'`, then this header would automatically propagate to the upstream unless you explicitly told the api definition to delete that header.

**Comment by david972** [comment]
> Service Discovery is intended to enable Tyk to discover how to route your API to the upstream. **You** do not make any service discovery calls, Tyk does this automatically as per the API Definition, and the `query_endpoint ` is responsible for returning a list of upstreams to proxy to.

yes. I've got that and what I suggest is that the service discovery call includes the headers from the request.
Like this the list of the upstreams to proxy to can be different according to the headers content

**Comment by buger** [comment]
Ah I see now 🤔 
Are you talking about some custom made service discovery, or about some product which supports such flow?

Implementation will be more complex then that, because service discovery does not get called for each request. It has a caching layer. So it will also need option to have HTTP header as a cache key or similar.

**Comment by david972** [comment]
> Are you talking about some custom made service discovery, or about some product which supports such flow?

Some custom made service discovery.

> Implementation will be more complex then that, because service discovery does not get called for each request. It has a caching layer. So it will also need option to have HTTP header as a cache key or similar.

🤔 yeah not sure it would be a problem in my case. But yes we need to cover all cases.

**Comment by david972** [comment]
what is invalidate the cache and then do the call ?

**Comment by buger** [comment]
At the moment it’s impossible.

The way to implement what you want right now is to have a Go plugin which will have service discovery logic inside and dynamically change target URL of api for each call

**Comment by andyo-tyk** [comment]
Hi @david972,
We welcome PRs from the community so would definitely be interested to see your proposal in code, to better understand whether it would fit into the Tyk product.
Thank you for supporting Tyk!

**Comment by andyo-tyk** [comment]
I'll close this ticket now. This feels like a very edge case that I can't see fitting onto our product roadmap - and, as suggested above, it can be implemented with a custom plugin.
