### ISSUE TITLE
Cache DNS to prevent DNS Spamming

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#495]
**UPDATED by @buger**

Go by default do not provide any DNS caching mechanism and on each connection does a DNS query. In the case when upstream does not support keep-alive connections, DNS query will be made on each HTTP request, which makes the huge load on DNS server. 

One of the cases to fix it on OS level by installing caching DSN proxy, but it is not possible in all the cases. So we need to introduce application level logic to cache DNS queries.

On first DNS query, for a given domain, it adds an entry to the cache. After we have a background job, which periodically goes through all cache entries and updates records in the background. Period of this job should be a configurable option, calling it TTL probably makes sense, however its job a bit different, so maybe we can find another name. 

Additionally, for removing stale records, we may also record last “query” time for a given domain and remove cache entries which were not used for last N seconds. 

## Dealing with multiple DSN records

DNS itself can return multiple records, and Go function which does DNS lookup returns array of IPs as well, see `net.DefaultResolver.LookupIPAddr`. So our cache should cache multiple entries as well. 

If we look at how Go internally works
https://golang.org/src/net/dial.go?s=10090:10150#L318, by default, it goes through list one by one, until a successful connection established. 

Another approach is so-called Round Robin DNS, where you obviously round robin through multiple records. 

I think we should actually support both, and add configurable option to specify DNS strategy: sequential or round-robin.

Interesting discussion on multiple DNS records https://webmasters.stackexchange.com/questions/10927/using-multiple-a-records-for-my-domain-do-web-browsers-ever-try-more-than-one

## Enable on API level
Not all APIs require such logic, only which has issues with DNS, so I think it makes sense enable this feature on API level while keeping cache TTL configured on gateway level. Should be added new API options called “enable_dns_caching”, and “dns_caching_strategy”, 

## Testing 

We include special DNS mock for writing unit tests which require multiple domains. In case of this task, this mock should be extended, to actually pass callback which customizes DNS server response, to return multiple records or similar, depending on test logic. 

See `initDNSMock` function in helpers_test.go

**Comment by mvdan** [comment]
Perhaps something like https://github.com/viki-org/dnscache, but that package seems abandoned.

https://golang.org/src/net/dnsclient_unix.go also has a TODO about a small cache.

**Comment by buger** [comment]
From what I see it should not be a problem to implement. Resolving DNS record can be done using `net/#LookupAddr` and caching itself can me smth like:

```
http.DefaultClient.Transport = &http.Transport {
  MaxIdleConnsPerHost: 64,
  Dial: func(network string, address string) (net.Conn, error) {
    separator := strings.LastIndex(address, ":")
    ip, _ := dnscache.FetchString(address[:separator]) <- I took this from dns cache example
    return net.Dial("tcp", ip + address[separator:])
  },
}
```

So we do not need dnscache, because it was written before Go had `Lookup*` functions.

We just need to write a proxy function which cache dns lookups in map for some short period of time, like 1s. Should be configurable I guess, and maybe be 0 by default. After we have cache, we just need to override Http dial function.

**Comment by mvdan** [comment]
@buger you're right, good spot. Since this seems to be fairly important for performance, I'll try to get to coding this soon.

Some out-loud design points:

* Why do you say we don't need `dnscache`, but you use it in the sample code? I assume you mean we'd implement the `dnscache.Fetch` line ourselves.
* For the sake of simplicity, I'm thinking of a `map` guarded by an `RWMutex` that gets cleared every N seconds. This should guarantee that our cache is at most N seconds behind and we don't have to worry about refreshing it in parallel.
* I think a default of many seconds like `5s` or `20s` would be saner than `1s`, since DNS records don't change that often and we don't want to grab the lock and block the cache often.
* What should a value of `0` be? Caching forever, or no caching at all? We could also make `0` be caching forever and `-1` be no caching at all, or the opposite. Also worth noting that caching forever is not a good idea in any scenario, as you'd want to instead cache for a day or some other very long period.

**Comment by buger** [comment]
I meant that we do not need `dnscache` because net package already does the job, treat code snippet as pseudo code.

Also, I realized that we already have data structure for this purpose: `"github.com/pmylund/go-cache"`. It is already used by Tyk in a lot of places and does the job.

> What should a value of 0 be?
Not caching at all, this will be a way to turn feature off

**Comment by matiasinsaurralde** [comment]
This package might be useful and looks newer than `dnscache`, it modifies the `DefaultResolver`: https://github.com/benburkert/dns/blob/master/init/init.go

**Comment by asoorm** [comment]
@buger @dencoded @matiasinsaurralde @lonelycode 

I think:

* Honour DNS TTL by default.
* Ability to disable DNS caching explicitly
* Ability to explicitly override cache ttl

```
{
  ...
  "dns": {
    "disable_cache": bool,                  <----- default false / nil
    "ttl_override_seconds": int,            <----- default 0
  }
}
```

| Config  | Output |
| ------------- | ------------- |
| `dns` object not set  | respect DNS TTL |
| `dns.disable_cache: false` | respect DNS TTL |
| `dns.disable_cache: true` | Disable Caching |
| `dns.ttl_override_seconds: 5` | Cache for 5s (assuming `disable_cache` is nil/false) |

Questions:

1. Any thoughts on above
2. Should this config be per upstream service / per gateway?

**Comment by buger** [comment]
Maybe instead explicitly enable caching, this at her than disable?

**Comment by asoorm** [comment]
@NicciCz - Useful to hear your thoughts on this?

**Comment by buger** [comment]
Updated task details based on talk with @evityuk

**Comment by evityuk** [comment]
By using a dns record's ttl from dns lookup call([see](https://play.golang.org/p/65hFuth1s_2) a line#33), we can omit storing additional configurations(both per api and global) on gateway side. 
Should we add that functionality with this issue or with the next one(and deprecate current configs) ? 
Current implementation store cache values globally and doesn't stored on per api basis. 

@lonelycode  @buger

**Comment by buger** [comment]
@evityuk do not think we should use DNS TTL values, because in most of the cases it is not the value you can configure, or set to the low enough value.
