### ISSUE TITLE
Deploying an OpenAPI 3.0.3 API definition with format: keywords in JSON schema is failing

### ISSUE THREAD

**Issue by DavidBiesack** [TykTechnologies/tyk#5388]
**Branch/Environment/Version**
- Branch/Version: Stable OSS
- Environment: On-prem

**Describe the bug**

We're importing an OpenAPI 3.0.3 document into Tyk.
Tyk is rejecting it: 

```json
{
    "status": "error",
    "message": "invalid components: unsupported 'format' value \"text\""
}
```

**Reproduction steps**

import the OpenAPI document at this gist: https://gist.github.com/DavidBiesack/17b15294c55ebc8e2af9188dc0b53e0b saved in `openapi.json` : 

```sh
curl --location \
     --request POST 'https://tyk.example.com:443/tyk/apis/oas/import?upstreamURL=https://api.example.com&listenPath=/text' \
     --header "x-tyk-authorization: $TYK_AUTH" \
     --header 'Content-Type: text/plain' \
     --data @openapi.json
```

**Actual behavior**

```json
{"status":"error","message":"invalid components: unsupported 'format' value \"text\""}
```

**Expected behavior**

no error.

OpenAPI allows using other `format` values, as per https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md :

> Primitives have an optional modifier property: `format`. OAS uses several known formats to define in fine detail the data type being used. However, to support documentation needs, the `format` property is an open `string`-valued property, and can have any value.

Question: Is there a query parameter on that POST operation to disable/bypass validation? We have an OpenAPI document that is already validated via Spectral and other linting.

**Comment by lghiur** [comment]
Hello @DavidBiesack, 

Thanks for raising this up with us.

We've already fixed this bug in the latest minor version release of the Gateway. To get everything running smoothly again, we suggest upgrading to the latest version (5.1.0/5.1.1). It will fix this issue.

* One thing to keep in mind: downgrading back after the upgrade can be a bit tricky and might cause compatibility issues. So, it's best to stick with the latest version once you've upgraded. 😊 
* As OpenAPI support is still (but close to be out of) in experimental state, just to be on the safe side, it's always a good idea to back up your APIs data before the upgrade, so that you can potentially restore to their initial state.

Let me know if this works with you!

**Comment by DavidBiesack** [comment]
> lghiur

yes, Tyk OSS oas import with custom format: keywords in schemas is working for us with 5.1.1

**Comment by lghiur** [comment]
@DavidBiesack thanks fro the updates! I'll close this issue and mark as solved
