### ISSUE TITLE
Add option to remove api token query param from cache key

### ISSUE THREAD

**Issue by gwshaw** [TykTechnologies/tyk#552]
**Feature**
It appears that caching with an api token query param includes the api token in the cache key. That make the cache ineffective for shared data, which is the largest class of data we serve right now. In fact, we specifically don't cache almost any non-shared data as it contains PII (personally identifiable information), and so that there are no issues with cache updating or the info being stored anywhere on the net.

The caching interface needs an option to remove the param specified as the api token from the query string.

**Comment by buger** [comment]
This definitely makes sense! But not sure what is the best way to achieve it. 

Simplest approach will be not using query params, and instead, use headers. But well it requires changes on your side, which is not desirable.

Another option, if you do not have too many URL's, you can set URL rewrite rule per URL, and remove token param. Not extensible and hard to manage, but available even now.

For sure worth mentioning that this issue can be solved by writing own middleware, in the language of your choice, which can handle any logic. Also already available if using on-premise or hybrid versions.

One of the options is to somehow mark API as stateless, so we do not maintain our internal cache per token, and token does not get passed to your server. Or as you mentioned just add configurable option to not send token to the origin server if it was included into query string (should we also not send header based auth tokens?). 

More extensible will be adding more general "Anonymization" middleware, where you can globally remove/rewrite URLs and headers. 

What do you think?

**Comment by gwshaw** [comment]
- Headers are a bit more cumbersome to use and are not part of our current APIs.
- We have >150 endpoints so rewriting is not an option and costs significant performance.
- Looking at the source, I see now that we could move the query param into a header in middleware to pass it into the auth part of the system because this happens before the caching middleware.
- I suggest that a better growth path for Tyk, as mentioned in other issues here, is plugins. One possibility would be to eliminate the option for api token in a param and add a performant plugin for end-users to add to remove the api token from the query params and put it in the desired header. Having struggled with the Tyk documentation, one large advantage of this approach is the encapsulation and ability to document it well in one place. Growing around this way with best-practice plug-ins give end users many good examples of how to grow the system themselves. Having ability without sufficient examples of how to use it is not that useful.

**Comment by lonelycode** [comment]
@gwshaw you may have missed this part of @buger's suggestion: 

> For sure worth mentioning that this issue can be solved by writing own middleware, in the language of your choice, which can handle any logic. Also already available if using on-premise or hybrid versions.

You can write your own plugin for Tyk in JS, Python, and Lua as native plugins and any gRPC supported language: Java, .Net, Ruby, Go, etc.

These can run post-auth (and so pre-cache). There are reference implementations [here](https://github.com/TykTechnologies/tyk-awesome-plugins) for plugins our team has built. Docs are on our site under "extending Tyk".

Tyk is architected this way precisely for performance reasons (code is integrated) and to provide a solid feature set for a variety of purposes so that users can get up and running quickly, not to fulfill a niche requirement for every single user - if you don't want to write a plugin, then you could just modify and compile the cache middleware to strip your query Param, Tyk is open source after all and this is a trivial change to cover your specific use case. 

Or use could use the custom middleware capability we already provide that offers a wide spectrum of capabilities to fulfill this requirement.

**Comment by lonelycode** [comment]
@buger to actually help address this requirement and your question: I think an anonymiser middleware that can be given a bunch of directives (headers, body regex, query string param keys) to remove or redact might be best, for ease of use, there could be an option to pre-set the current auth mechanism used by the api definition, but since other personally identifiable information may be available in the request then we should widen it out.

This should be a global MW so that it only needs to be set once

Also it will help where users are recording the full body data, because then it would be possible to store the anonymised data based on customised rules...

**Comment by QuduSEC** [comment]
@buger, @lonelycode I asked about this at the support.tyk.io #799 But support for some reason, did not respond.

Supports caching with tokens and without, is really very important. I think the problem can be solved in two ways:

1. Implement support schemes, by analogy with nginx.
2. Add support for exception named query parameters. For example: exclude access _token
