### ISSUE TITLE
Extend CoProcess plugins to support Go 1.8 plugins

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#553]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
Tyk CP plugins do not support go plugins

**What is the expected behavior?**
We should support Go plugins

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All.

Checklist:
- [x] Gateway implementation
- [x] Build env
- [ ] Docs

**Comment by mvdan** [comment]
Do we have any sort of coprocess plugins in Go right now, or is it all Python/Lua/js?

**Comment by matiasinsaurralde** [comment]
@mvdan At the moment you can write a plugin using any language that supports Protocol Buffers / gRPC, including Go, pretty similar to [this](https://github.com/hashicorp/go-plugin#architecture).

**Comment by mvdan** [comment]
Also worth noting that we can't add this for another 5 months at least, until 1.9 is out and we can drop 1.7 support.

And support for them in 1.8 is only available in Linux. But since we don't plan on extending support to *BSD, Mac or Windows anytime soon, that should not be a problem.

**Comment by buger** [comment]
Need to check if it is already done and check status https://github.com/TykTechnologies/tyk-plugin-demo-golang

**Comment by mvdan** [comment]
Different things as far as I can see - both would run Go code, but that repo is using grpc, while this is about native Go plugins.

**Comment by matiasinsaurralde** [comment]
@mvdan is right, the above sample uses the current plugin architecture, so it's a gRPC server written in Go that implements the dispatcher service.
I did an experiment with actual Go plugins months ago, but we were discussing the idea of using them as part of the middleware chain directly (not using/loading them using our current architecture: bundles, etc.).

**Comment by buger** [comment]
@dencoded transferring to you.

General idea is to come up with a proper spec for this task, gather all requirements, and do the proper PoC. @asoorm work should be a good start https://github.com/TykTechnologies/tyk/pull/1868 (feel free to use same branch if you want)

I think maybe we could extend direct middleware interface here, with `ProcessRequest` and etc. 

Also think about developer experience. It would probably mean creating a separate docker image which is used to build tyk at our CI and for building plugins themselves (since they are need to be build at the same env). 

Also, we need to focus on developer experience as well, and probably docker image should provide smart entry point where you can pass Go code, and get `so` as output. Maybe just use plain STDIN and STDOUT, like `docker run -i ... < plugin.go > plugin.so`, or similar.

**Comment by buger** [comment]
Additionally I have a feeling that there is no easy way to access parent process functions from inside plugin, and maybe it make sense to reuse same interface as we have for grpc plugins, when you have access to MiniRequestObject, session, context and etc. as function arguments. We also need to think about helper functions, we may need to expose, like set/get helpers, similar to rest of plugins.

**Comment by lonelycode** [comment]
This echoes a lot of the stuff I found actually: 

https://medium.com/@alperkose/things-to-avoid-while-using-golang-plugins-f34c0a636e8

**Comment by buger** [comment]
Yeah, we need to start with Ops part first and find the reliable way to build plugins, before actual architecture. If the plugin needs to be re-compiled, each time when we do a major update, this should be totally fine (even if minor). One of the possible ideas:

1) For each major Tyk version have a separate tag in our Docker build env (just created at https://github.com/TykTechnologies/tyk-build-env/)
2) When a plugin gets build, version number gets embedded into its binary code (via LD_FLAGS is the easiest way), and when plugin is loaded we do a runtime compatibility check, and if major plugin version differs from Tyk major version. In most of the cases it will fail even before this check, but having additional safeguard can help. 
3) When the plugin gets build, it probably use some smart entry point, or bash script, which runs docker, and it requires you to specify Tyk version, for which you need to build your plugin. It checks out related version of Tyk from the GitHub.
4) We limit plugin to consist only from the single fil. In order to avoid "mounting" files, just read its content from STDIN. When script reads from STDIN, it creates plugin.go file inside Tyk folder, created in the previous step, and it runs `go get` for it: if plugin use some package already used by Tyk, it will re-use it from vendor, if not, download a new one, but the main idea that we will not have vendoring conflicts. 
5) We run `go build` and specify only this single plugin file, and run this command inside Tyk directory, to achieve the same env. If its build, output to STDOUT content of the plugin.

**Comment by buger** [comment]
@dencoded merged PR 👌 

Now we need build env and docs on it.
