### ISSUE TITLE
Tyk Extension Framework

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#554]
Using Go 1.8 plugins users should be able to extend and modify any publicly defined function in the Tyk code base (or a wide base of them) using plugins they develop themselves.

The purpose of this feature is:

- To make Tyk more flexible
- To empower users to make the gateway work for them
- To move beyond middleware into full customisation
- To move from gateway to platform

This ticket serves as a discussion of what this framework will look like and how  it will work, @matiasinsaurralde will be taking point because of his prior experience with CP stack.

**Comment by mvdan** [comment]
While this is a great idea, I worry about stability. Middleware and coprocess plugins are clear, people can write them for 2.3 and they will work in 2.4 and 2.5 and so on.

If we make many of the public funcs/methods configurable, that means we have to keep their signatures and functionalities stable - otherwise, any Go 1.8 plugins that people wrote would no longer work.

What about abstracting away chunks of code with interfaces, and making those replaceable with a Go plugin? As a silly example, if the logger was behind an interface, that would be a candidate. As long as we don't modify the interface, we won't break backwards compatibility.

**Comment by buger** [comment]
Well indeed "To move beyond middleware into full customization" sounds too risky and ambitious. I would say we need to start with exactly same functionality which we have for current middleware.  

Also, do not forget that Go based plugins can't use methods of the caller. You can only call methods exposed by plugins. So we define that plugin should export some specific functions like "ProcessRequest" or maybe export sort of "Middleware" object. But the basic idea we should provide Go package for writing such plugins, which strictly says how plugins should be made, which interfaces should be used, and which functions/objects should be exposed.
