### ISSUE TITLE
[TT-10384] Is Tyk (gateway) affected by CVE-2023-44487 ?

### ISSUE THREAD

**Issue by martin-neotech** [TykTechnologies/tyk#5672]
**Versions of Tyk:** 4.x and 5.x

CVE-2023-44487

The HTTP/2 protocol allows a denial of service (server resource consumption) because request cancellation can reset many streams quickly, as exploited in the wild in August through October 2023.

https://www.cve.org/CVERecord?id=CVE-2023-44487

Is Tyk (gateway) affected by this ?

Is there any configurations for the self hosted that should be considered ?

Thanks

**Comment by martin-neotech** [comment]
https://github.com/golang/go/issues/63417

**Comment by andyo-tyk** [comment]
Hi @martin-neotech,

Sorry for the delay getting back to you on this.

Docker Scout assessment of the Tyk binaries suggests that the 4-LTS and 5-LTS versions are not affected, as they use Go 1.16 where HTTP/2 support has to be manually enabled. Within Tyk we have a Gateway configuration option ([enable_http2](https://tyk.io/docs/tyk-oss-gateway/configuration/#http_server_optionsenable_http2)) that enables HTTP/2. We advise that you disable this to mitigate the impact of CVE-2023-44487.

We are working on a solution for latest feature branch of Tyk (5.2.x) as this uses a newer version of Go where HTTP/2 is enabled by default.

**Comment by andyo-tyk** [comment]
Hi @martin-neotech 

Tyk has a configuration [option](https://tyk.io/docs/tyk-oss-gateway/configuration/#http_server_optionsenable_http2) to disable HTTP/2 - this will mitigate the risk of this vulnerability in all current versions of Tyk, though of course there might be a performance impact from use of HTTP/1.1 rather than HTTP/2.

The config flag is: `http_server_options.enable_http2`
You can also use the environment variable: `TYK_GW_HTTPSERVEROPTIONS_ENABLEHTTP2`

We recommend that you set this to `false` to restrict Tyk to using HTTP/1.1, avoiding the DoS risk.

The vulnerability lies within the core Golang `stdlib` package used by Tyk; we are working on upgrading this in the latest Tyk feature branch (5.2.x) but at present a Go upgrade is out-of-scope for the LTS version (5.0.x).
