### ISSUE TITLE
IP Whitelist can be simply fooled with "X-Forwarded-For"

### ISSUE THREAD

**Issue by silentfishwm** [TykTechnologies/tyk#624]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Enable IP whitelisting for an API, specify IP address 192.168.1.100, make a request to the API with "X-Forwarded-For" as the specified IP. The request passed through.

**What is the expected behavior?**
The request shouldn't pass through. 

With current behavior, IP whitelisting feature simply doesn't work because it can be easily bypassed...

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Described above.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.99

**Comment by buger** [comment]
Thank you for reporting! 

Do you have any suggestions how to fix it? I assume some kind of option to disable `X-Forwarded-For` check? If so, in this case it will stop working with proxies...

**Comment by silentfishwm** [comment]
Yes I suppose an option would be preferred, so that we have a choice. 

But from my viewpoint, it makes little sense for API publishers to enable IP whitelisting if they allow arbitrary proxies - the IP whitelisting doesn't put effective restriction anyway and its name "IP whitelisting" is somewhat misleading.

Therefore, my humble opinion is, IP whitelisting is an extreme access control which should't be used along with arbitrary proxies at all. If both proxies and IP restrictions are necessary, then a practical approach would be whitelisting the proxy IPs.

**Comment by mvdan** [comment]
An option makes sense - one that would tell whether or not to ignore `X-Forwarded-For` when using IP whitelists.

Keeping it on makes sense not only as a default to not break backwards compatibility, but also in cases where users really want to use a whitelist and control the proxy, e.g. if tyk is behind nginx. In those cases, if they trust their proxy and it always sets this header, it does work as intended.

But if tyk isn't behind a proxy at all, it should be off.

Perhaps this should be a "is tyk running behind a proxy?" option. Because using `x-forwarded-for` in any other scenario is equally wrong - it's a user fooling the gateway about whether or not it's running behind a proxy.

**Comment by lonelycode** [comment]
It's a bit tricky, since the XFF header can be arbitrarily added by a client, it's not a viable check to just ignore it or include it, since most servers run behind a load balancer and most of those are proxies.

Strictly speaking, we should have a list of allowed proxies that need to be present in the XFF header, this way at least we can validate the chain. Also, we should not allow duplicate entries in the XFF chain, since if the XFF header is meddled with client side, your real proxies should still append their own values, this should detect spoofing... at least I think so :-/

**Comment by buger** [comment]
This changes should be applied to the dashboard as well.

**Comment by kcq** [comment]
Whitelisting allowed proxies could be a bit brittle (because it relies on hard coded IP addresses, which might be hard to control in dynamic cloud environments), but it's a nice advanced feature. The standard way should be based on the number of proxies you trust. TrustProxy = 0 would mean that you don't trust any XFF data. TrustProxy = 1 would mean you trust the last proxy in the chain, etc.
