### ISSUE TITLE
`/tyk/keys/:keyID` allows accessing any key data even if scope limiter to specific `api_id`

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#629]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
`/tyk/keys/:keyID?api_id=:api_id` return key data even if the key has no access to this API.
**What is the expected behavior?**
It should check if key have access, and return error if not
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
This bug make sense when Tyk used with Dashboard. Create multiple API's, and single Key attached only to one of them. `/api/apis/:apiId/:key` endpoint will return key data for any of API's within organization, even if the key has no access to this API. Dashboard internally just query Tyk API, so issue located in this repository.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by lonelycode** [comment]
This is not a bug, it's how it's supposed to work.

The api id is not a filter, it specifies the storage back end to use to update the token.

Because it is possible to have different auth and session back ends for different apis.

**Comment by buger** [comment]
@lonelycode but what dashboard behavior? I it is definitely not expected.

**Comment by lonelycode** [comment]
So in the dashboard, in a default setup, will hash tokens, so it will not list them for editing (this might change), instead you need to search for them.

The search screen for the tokens will [group APIs by their session provider](https://github.com/TykTechnologies/tyk-analytics/blob/release-1.3/webclient/app/scripts/controllers/api_keys_choice.js#L24) and then generate a [search box for each session back-end](https://github.com/TykTechnologies/tyk-analytics/blob/release-1.3/webclient/app/views/api_key_list_choice.html#L35).

So a user that has generated a key for API 1 (redis) or API 2 (LDAP), will need to search for it against one of the two back-ends.

If they need to edit a key that has access to API 1 and API 2, they can use *either* search, because the write is handled by the gateway, it will [iterate through all ACL entries](https://github.com/TykTechnologies/tyk/blob/master/api.go#L105) and then call the update function on [each session provider](https://github.com/TykTechnologies/tyk/blob/master/api.go#L130).

The benefits here are that a local dashboard, with a custom gateway, that has a custom back-end for a specific API, can still mange that token via the dashboard so long as they have filled in the write-specific functions of the interface (so far this doesn't exist, our [demo ones are read only, e.g. LDAP](https://github.com/TykTechnologies/tyk/blob/master/ldap_auth_handler.go#L121). But that doesn't mean it isn't possible, it's how we switched from redis to redis cluster, we just wrote to the interface.

To add to the confusion, note that there are *two* back-ends per API, an auth back end and a session back end.

Auth back-ends provide raw data from a master (authentication) and session handlers provide authorisation, the best example is the RPC handler, authN is provided by an MDCB server and authZ is provided by the redis cache locally. 

(since MDCB is itself backed by a master gateway backed by redis means it is literally a bridging service, but it *could* be any auth back-end so long as the write functions are implemented).

I agree it is confusing, we have a lot of users expecting the query param to be a filter, when in fact it should be a back end, so maybe, it may be worth adding a new param name that is also respected called `backend_provided_by` and stop using the other filter, then deprecating it in a major version, also, if it is not provided, we should assume redis (I've always planned to do it and never got round to it).

Hope that ramble made sense... :-/

**Comment by mvdan** [comment]
If this was confusing to one of our devs, perhaps this "api id is not a filter" should be in the docs?
