### ISSUE TITLE
Redis driver replacement

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#667]
**Do you want to request a feature or report a bug?**
Feature/enhancement

We're currently using [redigo](https://github.com/garyburd/redigo) and [redigocluster](https://github.com/TykTechnologies/redigocluster) to handle our Redis interactions.

Switching to a more active package like [go-redis](https://github.com/go-redis/redis) (as suggested by @mvdan) is an interesting option, it includes cluster support as well.

**Comment by mvdan** [comment]
Thanks for opening the issue. I agree that this isn't pressing and shouldn't delay 2.4. At the same time, we don't want to stick with redigocluster for long. Some issues like #520 could be caused by either of these not-very-common libs.

**Comment by lonelycode** [comment]
We can actually implement this in parallel, to support redis with a new driver we just need to implement the `StorageHandler` interface with the new driver and add a selector for it as a name. 

There might be some places where a Redigo cluster driver is explicitly called which would need to be weeded out, but I don;t think there's many.

This should also port because the other libs base their implementations off a variation of the `StorageHandler` interface.

Note this would have a major impact on MDCB too.

Worth doing IMO, we can side-load it instead of replacing it, then we can canary it with out owned network.
