### ISSUE TITLE
Maximum session lifetime

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#681]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
Currently the global session lifetime supersedes everything (expires lifetime, etc.).

**What is the expected behavior?**
We should use the `ForceGlobalSessionLifetime` and enforce a maximum lifetime value.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All versions.

**Comment by buger** [comment]
@matiasinsaurralde can you add a bit more context. In which cases "expiring" sessions will work? 
I mean if we expire session, user API access will stop working.

**Comment by mvdan** [comment]
If it's one of us opening issues, let's use `Do you want to request a feature or report a bug?` as a label directly to avoid duplicate work.

**Comment by lonelycode** [comment]
In this case we are talking about the TTL of the session object (token data) stored in redis.

This is different from the expiry - since a token can continue to exist, but be expired - and so it's expiry can be extended and the token continue to be used. Once the token session is removed from redis because of the TTL, this can't be done, the whole token needs recreating.

There is a function called GetLifetime() which handles this for us at the moment, you can set TTL on the token via a global override, an api-level override or a value stored in the session object itself.

However, if a token expires later than the TTL, then the TTL should actually take that into account in order to preserve the data just in case.

So in a long running gateway instance, there is a chance that your key store will fill up with expired keys because no global TTL was set. But if you set a global TTL then tokens that should never expire (expires:0), should not have a TTL. The same goes for a token that has an expiry in 5 days, but the TTL is 2 days.

**Comment by buger** [comment]
@lonelycode well, potentially it can really surprise the user. For example, one if his developer have not paid for some time, and get back, if we had TTL, his API key will stop working, and have to be re-generated.  

It is ok, if customer knows about it, but otherwise very confusing. I would propose making this TTL turned off by default, and it works only for very specific workloads. 

There rest is looking good, and rules described by @lonelycode sounds like a plan 👍

**Comment by lonelycode** [comment]
@buger agreed - it needs to be an opt in, not a default :-)
