### ISSUE TITLE
Proposal: a way to know if a set of gateways is done with a group reload

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#716]
Right now, when you fire a group reload to a gateway via `/tyk/reload/group`, it sends a pub/sub notification via Redis to all other gateways to do a hot reload. The HTTP GET returns 200 almost immediately.

We need a way to know if the whole set of clusters is up to date after that reload. Proposed by @lonelycode in #703.

Some ideas:

* Endpoint that tells what each node's last reload time was (proposed by Martin in the issue above)
* Endpoint that tells what nodes haven't been reloaded since a time T (empty list == up to date)
* Endpoint that tells whether a group reload identified by ID has been finished in all nodes
* Make the group reload endpoint optionally block (with whatever underlying method)

/cc @buger

**Comment by lonelycode** [comment]
The reload ID is good - it means that audits can be done and validated, if the reload endpoint returns an OK / 200, the reload ID and the endpoint to poll for which nodes have completed, so:

```
{
    "status": "ok",
    "reload_id": "grl-321cca81-fc0d-400d-b3e3-99168b933bf3",
    "time": "1493851640",
    "status_url": "/reload/group/status/grl-321cca81-fc0d-400d-b3e3-99168b933bf3"
}
```

Then if you visit this URL it returns a list of the nodes that have sent a reload notification. All the gateways would need to harvest/collect these passively and store them in memory for a while (maybe in a time-limited cache).

We could go further and extend the `status/` root endpoint to include a listing of timestamp / caller IP / reload ID and nodecount (e.g. 5/5). We keep data for an hour.

(but that might be for a later time).

**Comment by mvdan** [comment]
I agree on reload IDs - I don't want to use times because they introduce too much flakiness. What if times aren't in sync? What if two reloads happened in the same second? Do we use the time when the HTTP GET was received, or when the pub/sub message was sent? etc.

> We keep data for an hour.

I was thinking more along the lines of keeping the last N group reload IDs. That way it's a lot easier to know that we won't be using tons of memory if group reloads get spammed. And for users that won't spam it, keeping e.g. the last 50 IDs will probably mean way more than the last hour.

**Comment by lonelycode** [comment]
The time stamps would be from the gateway at the end of the relod procedure - they would be nothing more than informational. Time sync wouldn't be critical, but if server 1,2 and 3 are all within 5ms but then server 4 is 5s that's an outlier that might need investigating.

As for time, dump the data into redis then it won't mater, they aren't large objects so memory overhead would be minimal even if it lives in ram. 

The thing is, reloads from the dashboard happen all the time (every time you save or update an api or policy, which happens loads), so that cache of n reload becomes swamped with data from one user that can't make up their mind and offers no meaningful insight. 

I'm not so bothered by the list, we can go with the most efficient option for now and get feedback.

**Comment by mvdan** [comment]
This isn't urgent and I've got enough stuff to do for 2.4, so pushing back to 2.5 for now.
