### ISSUE TITLE
Add a route variable to the middleware context

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#728]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
It currently isn't possible get access to a route variable to the JSVM (or any other middleware) context.

**What is the expected behavior?**
If middleware needs access some url param for its logic, it has split the path, and extract attribute manually. 

Tyk allows adding patterns to the URL's like this: `/widgets/{id}/{resource}`. Here is what Tyk docs say about it:
> A path can contain wild cards, such as {id}, the actual value in the wildcard is not used (it is translated into a regex), however, it is useful to make the path more human readable when editing.

So currently these variables are just UX feature, and not available programmatically to middleware, or anywhere else.

It would be nice to have a map object with this extracted variables, available to middleware developers, so they do not have to extract them manually.

**Comment by lonelycode** [comment]
> From our perspective, this feature looks quite complex, and touch a lot of application parts. We should not just replace this named variables by regexp, but actually, store them somewhere, and make accessible to JS context.

This feature should happen in the context map middleware where we already do splitting and storing other data as part of the request lifecycle.

We can then shove the entire context into wherever it's needed.

This feature though is most relevant to the Virtual Path functionality, which is completely different to the dynamic middleware and currently is only Otto JS. 

So doing it "properly" is a big task if you reframe it as all plugins and VP. Which wasn't the initial framing of this feature or the request raised by the user.

Since MW is not designed for orchestration, but VPs are, we could just do it so that the virtual paths have access to the whole context namespace (like $tyk_meta) so they do not need to do a regex in interpreted js on every request, it is wasteful and slow, it makes good sense to make them available only in VP and then extending the feature out to plugins.

Let's not over complicate something that could be inherently simpler.
