### ISSUE TITLE
Access to same api but different endpoints

### ISSUE THREAD

**Issue by squiddle** [TykTechnologies/tyk#76]
This is a little bit related to issue #17 

Is it possible to have multiple endpoints for the same api, but give each developer and/or access key access to only one of these.

The use case is an API which is provided to different customers where each customer has its own completely separate systems. All API management would be done in tyk cloud, where each endpoint is deployed with the hybrid cloud deployment scenario.

So not only are multiple endpoints required, but endpoints must be able to be referenced in policys and key configuration to allow access for.

With the current system it looks like it would be necessary to manage one api (and one policy) for each customer.

**Comment by kohrVid** [comment]
Hi @squiddle,

Thank you for getting in touch and apologies for the delayed response. I'm actually going to close this issue as we seem to have implemented a feature like this since this was posted (it is currently possible to set up an API with multiple endpoints and manage their permissions using different policies). If you're unsure of how to configure your API in this way, be sure to let us know in the [Community Forum](https://community.tyk.io).

Kind regards,
Jess @ Tyk
