### ISSUE TITLE
More choices for Tyk gateway storage backend 

### ISSUE THREAD

**Issue by lyptt** [TykTechnologies/tyk#80]
Would it be possible to have in a future version the option to have a more persistent storage option for Tyk gateway data? 

Currently all of the keys are stored in Redis, which unfortunately is difficult to work with when tearing down and setting up our environments, and also when backing up and restoring data. 

Ideally we'd like to be able to keep all of this key data either in the same Mongo database as the dashboard, or alternatively a MySQL database.

**Comment by lonelycode** [comment]
It is possible, that's what the StorageHandler interface is for:

https://github.com/lonelycode/tyk/blob/master/storage_handlers.go#L30

We rely on Redis to provide a fast and atomic way to rate-limit and enforce quotas across a bunch of instances, so switching out whole-heartedly to another DB could impact key retrieval and latency (it's why we went with Redis in the first place).

We did put in a mechanism for exactly this scenario though where valid key storage that is separated from the session-handling. Tyk has a two-phase authorisation an authentication check:

- If Tyk finds the key in the session handler (Redis) it assumes that the key is authenticated and uses it
- If Tyk does not find the key in the session handler, it asks the auth handler if the key is valid, this component can have a _different_ storage engine, if the auth handler replies with a valid session object, that session object is copied into the session handler for further use.

This was actually first developed so that the logic that defines how a key is authenticated versus how it is extracted and processed for session use are separate, these two area actually interfaces `AuthorisationHandler` and `SessionHandler`, so they can be completely replaced with new logic if necessary. By default, they both use the same back-end.

But this functionality can also be hijacked, there's a nifty trick where you can just swap out the back end of this authentication operation. This is quite handy if you are maintaining keys outside of tyk, because you can set the session lifetime really low (e.g. 60 seconds), this would force keys to expire quickly and re-authenticate with the third party storage system. This is exactly how the [LDAP handler](https://github.com/lonelycode/tyk/blob/master/ldap_auth_handler.go) is meant to work, if you look at the code, it only implements the read operations, none of the writes.

The implications of this are: You will not be able to use the Tyk REST API to generate keys (or you could, but your system would then need to manually sync them to a new storage engine to ensure they are retrievable on a teardown). This makes sense, since you are separating authentication from authorization. You would also need to *remove* them when they are invalidated so they do not get re-synced.

A final option would be to bastardise the Redis session handler to push data into your third party storage on UpdateSession(), but then you break authentication/authorization separation.

Personally I find that injecting a read-only storage handler into the Auth Handler is the most elegant solution, configuring it super simple too, in the API Definition, here's the LDAP example:

"auth_provider": {
        "name": "",
        "storage_engine": "ldap",
        "meta": {
            "ldap_server": "test-ldap.yourserver.com",
            "ldap_port": 389,
            "base_dn": "dc=test-ldap,dc=tyk,dc=io",
            "attributes": ["cn", "description"],
            "session_attribute_name": "description",
            "search_string": "(cn=TYKKEYID)",
            "use_ssl": true
        }
    },

See how the storage engine and meta objects are the only things populated? All that tells Tyk to do is to init the default Auth Provider and use the assigned storage handler (ldap) for when it checks if a key is valid. 

Whipping up a quick read-only back-end is pretty simple, so the question is which DB to choose :-)
