### ISSUE TITLE
Improved healthcheck API

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#857]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
We have `/<api>/hello` endpoint, which returns 200 if API loaded. 

**What is the expected behavior?**
This type of health checking is not enough because it does not check redis/dashboard/RPC connectivity. We should check this stuff for each "hello" request, and return the meanungfull error if something wrong happened.

**Comment by mvdan** [comment]
Would this info only contain start-up status? I assume for each of redis/dashboard/RPC, we would have a "connecting", "connected" or "error" status - the last one potentially with extra information.

**Comment by buger** [comment]
It will dynamically call any backend it currently uses, so not only start-up status.

**Comment by excieve** [comment]
I think this should be re-prioritised and divided into two features:
 - readiness health check, which can be mostly as it currently is
 - liveness health check, which should be more advanced

Readiness check should be fast and respond with success as soon as the application fully starts, liveness check should return error on critical components failure. This maps to k8s `readinessProbe` and `livenessProbe`, where the former influences basic ability to accept traffic (critical for quick scaling and restarts) and the latter hints about whether the service is not healthy while already running and should be restarted. See [k8s docs on the subject](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) for more details.

Both should optionally be serving on a port different from the main router so that in case main is running with https, health-checks can still serve on http. This helps to avoid a situation where under heavy load restarts (due to inability to reach the port within timeout) create an even worse situation.
