### ISSUE TITLE
Add support for "id_extractor" to JS middleware

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#935]
**Do you want to request a *feature* or report a *bug*?**

Feature. Please add support for the id_extractor and JS "auth_check" middleware to interoperate.

**What is the current behavior?**

It seems you can't use "id_extractor" with JS middleware and an "auth_check" JS middleware function.

See: https://community.tyk.io/t/npm-and-jsvm-custom-basic-auth-plugin-more-details/1752/21?u=bitsofinfo

**Comment by matiasinsaurralde** [comment]
Hi @bitsofinfo, the JSVM middleware is completely separate from the rich plugins architecture (which is used by the ID extractor), we have a plan to unify it so that we can avoid duplicate code.
As we've noted in the forum, it's possible to implement similar logic using `ReturnOverrides` and other hook types.

**Comment by bitsofinfo** [comment]
not stale, these stale bots are ultra annoying

**Comment by andyo-tyk** [comment]
Thanks for this suggestion, as mentioned above it's on the list of feature requests for improving Tyk's custom middleware support, but evidently hasn't made it high enough up the list over the past six years. I propose closing this ticket due to its age, but will make a note to update with a comment as and when we address this request.

Please feel free to comment and I can re-open if you prefer.
