### ISSUE TITLE
Service Discovery

### ISSUE THREAD

**Issue by michaelsogos** [TykTechnologies/tyk#956]
Hi Guys,

We are implementing a microservice architecture with docker swarm and .net core web api; and as you know one of the most important component in this kind of system is a service discovery to proper manage failover containers and load balancing.

We love Tyk but seems that it lack this feature forcing us to add a new component like consul.io (or eureka, etc.), and is our opinion that it produce a double application installation for the same purpose, i mean that consul.io reply mostly of your feature (at least the most used by us) plus prometheus for analytics and alerting.

So our question is, why you don't implement a service discovery instead rely on external component?
There is a plan for this?

**Comment by lonelycode** [comment]
There isn't a plan to implement a service discovery system in Tyk in the short term. Though I can see the reasoning, we do have the capability to integrate with any system that provides a REST interface to handle service discovery though, so that might help (if you don;t want to install consul or etcd, you might just use a smaller homebrew API)

**Comment by letzya** [comment]
Has been implemented long time ago.
