### ISSUE TITLE
Add support to expose context variables to JSVM middleware

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#961]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

No access to context variables in JSVM middleware

I have a need to access some of the request context data as described here: https://www.tyk.io/docs/concepts/context-variables/

Particularly `remote_addr`, but this is not available in JSVM middleware

**Comment by bitsofinfo** [comment]
not stale

**Comment by andyo-tyk** [comment]
Thanks for this suggestion, it's definitely something we will consider so I have added it to the list of feature requests for improving Tyk's custom middleware support. I propose closing this ticket due to its age, but will make a note to update with a comment as and when we address this request.

Please feel free to comment and I can re-open if you prefer.
