### ISSUE TITLE
Enable initial REST to gRPC proxying

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#971]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
We can't proxy to gRPC endpoints directly.

**What is the expected behavior?**

1. I should be able to upload, or use a CLI command to generate a Go-plugin from a `protoc` file.
2. Reference this plugin name from my API Definition in a `grpc_endpoints` section in the MW.
3. Add paths to the `grpc_endpoints` configuration section that map to the services that are being proxied.

We could use [this library](https://github.com/grpc-ecosystem/grpc-gateway) to provide the base functionality of plugin creation since it already generates a `gw` object that just needs binding to a muxer.

**Comment by buger** [comment]
This project should be a nice base https://github.com/grpc-ecosystem/grpc-gateway

Also Google Cloud docs for their own feature https://cloud.google.com/endpoints/docs/grpc/transcoding

**Comment by buger** [comment]
I made some research and found that its actually doable to implement both GRPC -> GRPC, JSON -> GRPC and GRPC -> JSON proxying without Go plugins, by dynamically reading Protobuf definitions. And looking at how it works, this is how Google and Envy does it https://www.envoyproxy.io/docs/envoy/v1.5.0/api-v2/filter/http/transcoder.proto.html#envoy-api-msg-filter-http-grpcjsontranscoder

Basic idea that it is possible to generate language agnostic "pb" file which contains everything needed to parse protobuf message, using the`descriptor_set_out` argument of protoc: `protoc -I$(GOOGLEAPIS_DIR) -I. --include_imports --include_source_info \
--descriptor_set_out=proto.pb test/proto/bookstore.proto`

Next, ProtoBuffer provides API to dynamically load messages if you have such "pb" definition, example below in Java, but doable for Go too:

```
    FileInputStream fin = new FileInputStream("test.pb");
    DescriptorProtos.FileDescriptorSet set = DescriptorProtos.FileDescriptorSet.parseFrom(fin);
    Descriptor md = Descriptors.FileDescriptor.buildFrom(set.getFile(0), new  Descriptors.FileDescriptor[] {}).findMessageTypeByName("Person");
    return DynamicMessage.parseFrom(md, data);
```
https://stackoverflow.com/questions/4035027/generic-parsing-of-pb-in-java

The basic building blocks here is `DynamicMessage` and `findMessageTypeByName`, where you specify the name of the current protobuff class. Once you have this DynamicMessage you can iterate over its fields and do whatever you want. More over, this "pb" file can even be stored inside API definition, and uploaded by user via dashboard. Similary you can create object of any type, definited in "pb" file, only by knowing its name, e.g "selector".

The next part is configuring selectors on Tyk side, where we map objects to urls. And if we look at Google approach they provide 2 options to do this, 1) inside proto file 2) inside separate yaml config.
Option 2 is exactly what we looking for:
```
http:
  rules:
  ...
  #
  # 'GetShelf' is available via the GET HTTP verb and '/shelves/{shelf}' URL
  # path, where {shelf} is the value of the 'shelf' field of 'GetShelfRequest'
  # protobuf message.
  #
  # Client example - returns the first shelf:
  #   curl http://DOMAIN_NAME/v1/shelves/1
  #
  - selector: endpoints.examples.bookstore.Bookstore.GetShelf
    get: /v1/shelves/{shelf}
```
https://cloud.google.com/endpoints/docs/grpc/transcoding#configuring_transcoding_in_yaml

### JSON -> GRPC
Tyk can use exactly the same approach, as google does and you assign "GRPC plugin" to endpoint, where you specify "selector" of your protobuf definition. Since you know object type, you can create protobuf message based on JSON input and forward it to GRPC server. More over, you can just use body transform, to turn user input into GRPC supported JSON format. API should know if upstream is grpc, but it is quite easy to do, by supporting "grpc://" protocol format inside upstream urls. 

### GRPC -> GRPC
GRPC itself uses HTTP/2 transport, and @josh already doing HTTP2 evaluation, so we can officially support it. Protobuf format itself use headers to indicate method name, and we can just use advanced url rewriter on top of it, and route this requests to "loopback" which will do additional logic if needed. Additionally, since it is HTTP based, all our auth modes should work well when Tyk put on top of GRPC. 

### GRPC -> JSON 
Not sure how it is useful, just comes as a bonus. Since you have access to parsed protobuf message, you are free to serialize it into JSON, and advanced url rewrite like mentioned in previous step, but in addition use body transform plugin, which will know that input is GRPC, will serialize message to JSON, and you can use body transform to modify it as you want, and send to standard http endpoint.

**Comment by lonelycode** [comment]
You smart b%st%rd @buger, this is awesome research. 

Does sound like a lot of work though - will need planning and prioritising...

**Comment by shubhamranjan** [comment]
@lonelycode Is this possible now ? I can see support for gRPC gateway and gRPC passthrough proxy but not for REST to gRPC.

**Comment by joshblakeley** [comment]
not stale

**Comment by joshblakeley** [comment]
> @lonelycode Is this possible now ? I can see support for gRPC gateway and gRPC passthrough proxy but not for REST to gRPC proxying.

It is possible with a go plugin implementing something like https://github.com/grpc-ecosystem/grpc-gateway but not currently available natively

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap and we will ensure this is considered as we evolve the gateway's protocol mediation capabilities; I am closing the request here due to the age as it has become stale.
