### ISSUE TITLE
Tyk mutates header casing on JSVM request.SetHeader

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#975]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I do this

```
request.SetHeaders = {"x-my-header":"myvalue"};
```
Then if I do 

`request.Headers["x-my-header"]` its not found. Tyk camel cased it.... as "X-My-Header"

**What is the expected behavior?**

Leave the SetHeaders casing alone as the user specifies them

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

1.3.7/2.3.7

**Comment by mvdan** [comment]
This is sort of expected, as Go's net/http canonicalizes all headers when setting and getting them.

@matiasinsaurralde this is why I was mentioning that we should have used setter and getter funcs too - otherwise `req.Headers["foo"]` and `req.Headers["Foo"]` aren't the same, when they should be.

@bitsofinfo I'm not sure if we can fix this inconsistency while staying backwards compatible. In the meantime, I believe you can adapt your code to this behavior. In particular, always use Capitalized-Strings as your header names and it should work fine.

**Comment by bitsofinfo** [comment]
yes not a huge deal but more of an annoyance. These should be case insensitive

**Comment by mvdan** [comment]
@bitsofinfo indeed they should be case insensitive - as said above, I think this was an unintended design error. Would like to hear @matiasinsaurralde's opinions before we milestone this.

**Comment by bitsofinfo** [comment]
@mvdan fyi, writing/reading headers in ALL_CAPS makes no difference, tyk still camel cases everything and you must force fetch camel-cased

**Comment by lonelycode** [comment]
The camel casing comes from Go's parser, it automatically changes the case, so we don't actually know the original header case. 

The only option as @mvdan said is to use a getter and setter that filters this - but what gets proxies will probably still be camel cased.

**Comment by bitsofinfo** [comment]
not stale, these stale bots are ultra annoying

**Comment by andyo-tyk** [comment]
I'm reviewing old Github issues and found this in the Tyk docs: https://tyk.io/docs/tyk-oss-gateway/configuration/#ignore_canonical_mime_header_key

I believe this was implemented to address the issue you've raised in this ticket and so will close it.

If there is still an issue, please re-open.

Thank you for your support.
