### ISSUE TITLE
Can we view usage per user api key ? 

### ISSUE THREAD

**Issue by JnMik** [TykTechnologies/tyk#98]
Hello ! 

I see the Tyk dashboard offers an activity by key panel, but this seems to be the activity by API key, not the Developers keys. Any way to get the usage by developers key ? 

That would be useful to detect who's still using an old API that needs to be deprecated.

thx !

**Comment by lonelycode** [comment]
If you go to the developer's profile (portal developers -> developer) you can see the Apis they have access to, there is a link for each key in that view directly to the token analytics for that dev (they may have multiple tokens), so you can see their usage.
Not sure if that answers your question?

**Comment by JnMik** [comment]
Yup that page could definitely answer my needs, if I could make it work aha.

I generated an api key from the Developer Portal - Api Catalogue.
I runned a dozen of successful curls with that key, but the admin panel doesn't 
show any hits for that usage.

I think the stats are supposed to be instant like they are in the "Endpoint popularity" right ? 

So I must have something not working on my end..
An idea what it might be ?

**Comment by lonelycode** [comment]
Interesting - how is the API set up? Is the api that you are tracking a token based api, or open?
If it's open then very little will track, since there's nothing to tie data too :-)

**Comment by JnMik** [comment]
Hmm the API use Auth Token and the curls look like this :
curl  --header "authorization: 55e9af64c4545d0001000001af5e6a8f6ad940986caea4b7b8358060" "http://dk1.jmcyr.dev.lan:8080/mailing/1.0/ping"

response : {"status":"OK"}

**Comment by lonelycode** [comment]
Is the API actually set to use auth token? If you drop the header does it stop working?
What does the Stats by token table look like? Anything in there? Can you share a screenshot?

**Comment by JnMik** [comment]
The API is set to use the auth token yes.
http://screencast.com/t/3WMAEirVEr
http://screencast.com/t/bTu5HA7J

The activity by key is also increasing : 
http://screencast.com/t/1I2KAWr4dxs

**Comment by lonelycode** [comment]
The key that you are pin ting at here: http://screencast.com/t/1I2KAWr4dxs
Is different from the graph you screenshotted here: http://screencast.com/t/bTu5HA7J
Which one is going up?
When you select the key that seems to have an increasing request count, does it display a graph?
What are the time zones set to in the machines? Are the dashboard and Tyk gateway using the same time zone?
What happens when you increase the range to include one more day on the future?
Lots of questions - sorry, but it's a bit odd, because the analytics data that provides the increasing request count is the same that is used for the graph, just a different aggregation.
So the data is there, just not visualising for some reason.
Might be worth taking a look in your mongodb and pulling out the analytics data to see what it looks like...

**Comment by JnMik** [comment]
Hmm I just leave the office, but I'll give you more intel on this on tuesday for sure :)
